Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2023-12, with the labels that each got.

#878 [ALL] RELEASE v1.5.2
  README.md
Labels: 📑 문서, 🚛배포

#876 [FE] sse 발생시 팀 채팅 조회로직 제거 밑 이벤트 이용해 채팅 렌더링
  frontend/src/apis/feed.ts
  frontend/src/constants/query.ts
  frontend/src/hooks/queries/useFetchThreads.ts
  frontend/src/hooks/queries/useSSE.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#877 [FE] 공지에 사진 올라갔을 경우 UI 수정
  frontend/src/components/feed/NoticeThread/NoticeThread.stories.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.tsx
  frontend/src/components/feed/ThumbnailList/ThumbnailList.styled.ts
  frontend/src/components/feed/ThumbnailList/ThumbnailList.tsx
  frontend/src/components/feed/ViewableThumbnail/ViewableThumbnail.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#857 [FE] 스케줄 바를 드래그하여 수정할 수 있는 기능 구현
  frontend/src/components/team_calendar/CalendarDragScreen/CalendarDragScreen.styled.ts
  frontend/src/components/team_calendar/CalendarDragScreen/CalendarDragScreen.tsx
  frontend/src/components/team_calendar/FakeScheduleBarsScreen/FakeScheduleBarsScreen.stories.tsx
  frontend/src/components/team_calendar/FakeScheduleBarsScreen/FakeScheduleBarsScreen.styled.ts
  frontend/src/components/team_calendar/FakeScheduleBarsScreen/FakeScheduleBarsScreen.tsx
  frontend/src/components/team_calendar/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/team_calendar/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/team_calendar/ScheduleBar/ScheduleBar.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.styled.ts
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/hooks/schedule/useCalendarDragScreen.ts
  frontend/src/hooks/schedule/useScheduleBarDragStatus.ts
  frontend/src/types/schedule.ts
  frontend/src/utils/generateScheduleBarsByMousePoint.ts
  frontend/src/utils/test/generateScheduleBars.test.ts
  frontend/src/utils/test/generateScheduleBarsByMousePoint.test.ts
Labels: 💻 프론트엔드, 💡 기능

#885 [FE] 채팅 setQueryData 후 콘솔 추가
  frontend/src/constants/query.ts
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#886 [FE] 채팅 SSE의 setQuery의 데이터 타입 변경
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#887 [FE] sse로 받은 event data를 객체로 parse
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#889 [BE] 특정 기간을 지정해서 일정 조회 기능 구현
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/parser/LocalDateParser.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
  backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleException.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/MyCalendarScheduleController.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamCalendarScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MyCalendarScheduleAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamCalendarScheduleAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/MyCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/LocalDateParserTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/CalendarPeriodTest.java
Labels: 🍃 백엔드, 💡 기능, 중요도-상

#888 [FE] 채팅 변경되었을 시 스크롤 하단 볼 수 있도록 수정
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#898 [BE] 쿼리파라미터 카멜케이스로 변경
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/MyCalendarScheduleController.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamCalendarScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MyCalendarScheduleAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamCalendarScheduleAcceptanceFixtures.java
Labels: 🍃 백엔드, 🔨 리팩터링

#894 [FE] 팀 링크 레이아웃 버그 픽스
  frontend/src/components/link/LinkTable/LinkTable.styled.ts
  frontend/src/components/link/LinkTable/LinkTable.tsx
  frontend/src/mocks/handlers/link.ts
Labels: 🚨 버그, 💻 프론트엔드

#897 [FE] 변경된 일정 조회 명세가 작동하도록 팀 캘린더와 통합 캘린더 리팩터링
  frontend/src/apis/schedule.ts
  frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/hooks/queries/useFetchMySchedules.ts
  frontend/src/hooks/queries/useFetchSchedules.ts
  frontend/src/hooks/queries/usePrefetchMySchedules.ts
  frontend/src/hooks/queries/usePrefetchSchedules.ts
  frontend/src/mocks/fixtures/schedules.ts
  frontend/src/mocks/handlers/calendar.ts
  frontend/src/types/schedule.ts
  frontend/src/utils/generateCalendarRangeByYearMonth.ts
  frontend/src/utils/generateYYYYMMDDWithoutHyphens.ts
  frontend/src/utils/test/generateCalendarRangeByYearMonth.test.ts
  frontend/src/utils/test/generateYYYYMMDDWithoutHyphens.test.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#905 [FE] 일정 표시 문구 개선
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/utils/generateDateTimeRangeDescription.ts
  frontend/src/utils/test/generateDateTimeRangeDescription.test.ts
Labels: 💻 프론트엔드, 💡 기능
