Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2023-07, with the labels that each got.

#4 chore: 프론트엔드 프로젝트 초기 세팅
  frontend/.babelrc.json
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.prettierrc.json
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/auth.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/stories/Button.stories.ts
  frontend/src/stories/Button.tsx
  frontend/src/stories/Header.stories.ts
  frontend/src/stories/Header.tsx
  frontend/src/stories/Introduction.mdx
  frontend/src/stories/Page.stories.ts
  frontend/src/stories/Page.tsx
  frontend/src/stories/assets/code-brackets.svg
  frontend/src/stories/assets/colors.svg
  frontend/src/stories/assets/comments.svg
  frontend/src/stories/assets/direction.svg
  frontend/src/stories/assets/flow.svg
  frontend/src/stories/assets/plugin.svg
  frontend/src/stories/assets/repo.svg
  frontend/src/stories/assets/stackalt.svg
  frontend/src/stories/button.css
  frontend/src/stories/header.css
  frontend/src/stories/page.css
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/theme.ts
  frontend/src/types/theme.d.ts
  frontend/src/utils/arrayOf.test.ts
  frontend/src/utils/arrayOf.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: 💻 프론트엔드, ⚙️ 환경설정

#10 [FE] 공통 Text 컴포넌트 생성
  frontend/src/components/common/Text/Text.stories.ts
  frontend/src/components/common/Text/Text.styled.ts
  frontend/src/components/common/Text/Text.tsx
  frontend/src/types/size.ts
Labels: 💻 프론트엔드, 💡 기능

#12 [FE] 공통 버튼 컴포넌트 생성
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
Labels: 💻 프론트엔드, 💡 기능

#31 [BE] 프로젝트 세팅
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/team/teamby/teambyteam/TeamByTeamApplication.java
  backend/src/main/resources/application.yml
  backend/src/test/java/team/teamby/teambyteam/TeamByTeamApplicationTests.java
Labels: 🍃 백엔드, ⚙️ 환경설정

#37 [BE] 스케쥴 테스트용 더미데이터 추가
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
  backend/src/test/resources/h2-data.sql
Labels: 🍃 백엔드, 🤖 테스트

#38 [BE] 팀 플레이스 도메인 작성
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/Name.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepository.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceException.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/NameTest.java
Labels: 🍃 백엔드, 💡 기능

#41 [BE] 멤버 도메인 작성
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Email.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/ProfileImageUrl.java
  backend/src/main/java/team/teamby/teambyteam/member/exception/MemberException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/EmailTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/NameTest.java
Labels: 🍃 백엔드, 💡 기능

#42 [BE] NULL 입력에 대한 예외 클래스 변경
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Name.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/Name.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/NameTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/NameTest.java
Labels: 🍃 백엔드, 🔨 리팩터링

#43 [BE] 일정명 필드 vo 네이밍 변경
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Title.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/TitleTest.java
  backend/src/test/resources/h2-data.sql
Labels: 🍃 백엔드, 🔨 리팩터링

#44 [BE] 팀플레이스 테스트용 더미데이터 추가
  backend/src/test/resources/h2-data.sql
Labels: 🍃 백엔드, 🤖 테스트

#45 [BE] member & member_team_pace 더미 데이터 추가
  backend/src/test/resources/h2-data.sql
Labels: 🍃 백엔드, 🤖 테스트

#34 [FE] 공통 Modal 컴포넌트 작성
  frontend/.storybook/preview.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Modal/ModalContext.tsx
  frontend/src/hooks/useKeydownEffect.ts
  frontend/src/hooks/useModal.ts
  frontend/src/index.tsx
Labels: 💻 프론트엔드, 💡 기능

#48 [FE] Calendar 컴포넌트 UI 구현
  frontend/src/components/Calendar/Calendar.stories.tsx
  frontend/src/components/Calendar/Calendar.styled.ts
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/Calendar/DateCell/DateCell.stories.tsx
  frontend/src/components/Calendar/DateCell/DateCell.styled.ts
  frontend/src/components/Calendar/DateCell/DateCell.tsx
  frontend/src/styles/theme.ts
  frontend/src/utils/parseDate.test.ts
  frontend/src/utils/parseDate.ts
Labels: 💻 프론트엔드, 💡 기능

#47 [BE] refactor: @AllArgsConstructor & @NoArgsConstructor 추가 리팩토링
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/ProfileImageUrl.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Span.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
Labels: 🍃 백엔드, 🔨 리팩터링

#50 [FE] lint-staged git hook 추가
  frontend/.husky/pre-commit
  frontend/package-lock.json
  frontend/package.json
Labels: 💻 프론트엔드, ⚙️ 환경설정

#53 [BE] Bearer token에서 email을 추출하는 Argument Resolver 구현
  backend/build.gradle
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/member/configuration/AuthPrincipal.java
  backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberArgumentResolver.java
  backend/src/main/java/team/teamby/teambyteam/member/configuration/dto/MemberEmailDto.java
Labels: 🍃 백엔드, 💡 기능

#54 [FE] 캘린더 일정 등록 및 조회 모킹 구현
  frontend/src/apis/fetch.ts
  frontend/src/mocks/handlers/calendar.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/types/schedule.ts
Labels: 💻 프론트엔드, 🤖 테스트

#57 [BE] entity에 id를 제외한 나머지를 파라미터로 받는 생성자 작성
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
Labels: 🍃 백엔드, 🔨 리팩터링

#63 [BE] data.fix/be/data.sql 버그 fix
  backend/src/test/resources/h2-data.sql
Labels: 🚨 버그, 🍃 백엔드

#65 [BE] fix: 2개 이상의 테스트 실행시 h2-data.sql 오류 수정
  backend/src/test/resources/h2-reset-pk.sql
Labels: 🚨 버그, 🍃 백엔드

#66 [BE] RestAssured 의존성 추가
  backend/build.gradle
Labels: 🍃 백엔드, ⚙️ 환경설정

#69 [BE] AcceptanceTest 슈퍼 클래스 구현
  backend/src/test/java/team/teamby/teambyteam/common/AcceptanceTest.java
Labels: 🍃 백엔드, ⚙️ 환경설정, 🤖 테스트

#72 [FE] 캘린더 일정 제목 필드 변경 반영
  frontend/src/mocks/handlers/calendar.ts
  frontend/src/types/schedule.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#74 [FE] 스토리북 및 앱에서 svg 아이콘 사용 가능하도록 설정
  frontend/.storybook/main.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/svg/arrow-left.svg
  frontend/src/assets/svg/arrow-right.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/types/assets.d.ts
  frontend/webpack.config.js
Labels: 💻 프론트엔드, 💡 기능

#71 [BE] 일정 추가 기능 구현
  backend/src/main/java/team/teamby/teambyteam/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleRegisterRequest.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Span.java
  backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleException.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/ScheduleController.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepository.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceException.java
  backend/src/test/java/team/teamby/teambyteam/fixtures/ScheduleFixtures.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/SpanTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepositoryTest.java
Labels: 🍃 백엔드, 💡 기능

#76 [FE] h태그 및 cssProp 스타일 적용안되는 현상 fix
  frontend/src/components/common/Text/Text.styled.ts
Labels: 🚨 버그, 💻 프론트엔드

#82 [BE] 일정 추가 기능 문서화
  backend/.gitignore
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/schedule.adoc
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/ScheduleApiDocsTest.java
Labels: 🍃 백엔드, 📑 문서, ⚙️ 환경설정, 🤖 테스트

#86 [BE] Fixture, Test 한글 -> 영어로 리팩토링
  backend/src/test/java/team/teamby/teambyteam/fixtures/ScheduleFixtures.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/ScheduleApiDocsTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 🤖 테스트

#85 [FE] Pretendard 폰트를 추가하고, 기본 폰트로 적용되도록 수정
  frontend/.storybook/preview-head.html
  frontend/public/index.html
  frontend/src/styles/GlobalStyle.ts
Labels: 💻 프론트엔드, 💡 기능

#77 [FE] 캘린더 일정 조회 모달 UI 구현
  frontend/src/assets/svg/close.svg
  frontend/src/assets/svg/delete.svg
  frontend/src/assets/svg/edit.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/ScheduleModal/Schedule.styled.ts
  frontend/src/components/ScheduleModal/ScheduleModal.stories.tsx
  frontend/src/components/ScheduleModal/ScheduleModal.tsx
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#78 [BE] 멤버 인증 인터셉터 구현
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
  backend/src/main/java/team/teamby/teambyteam/member/exception/MemberException.java
Labels: 🍃 백엔드, 💡 기능

#80 [BE] 특정 일정 조회 기능 구현
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleResponse.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleException.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamPlaceScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/ScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/SpanTest.java
Labels: 🍃 백엔드, 💡 기능, 🤖 테스트

#96 [FE] 테스트 자동화 yml 스크립트 및 jest ci 테스트 명령어 작성
  .github/workflows/frontend-ci.yml
  frontend/package.json
Labels: 💻 프론트엔드, 🤖 테스트

#100 [FE] github actions ci 스크립트 node cache 수정
  .github/workflows/frontend-ci.yml
Labels: 💻 프론트엔드, ⚙️ 환경설정

#89 [FE] 일정 등록 모달 UI 구현
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.styled.ts
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/Input/Input.tsx
Labels: 💻 프론트엔드, 💡 기능

#90 [FE] 캘린더 피그마 디자인 반영
  frontend/src/components/Calendar/Calendar.styled.ts
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/Calendar/DateCell/DateCell.stories.tsx
  frontend/src/components/Calendar/DateCell/DateCell.styled.ts
  frontend/src/components/Calendar/DateCell/DateCell.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
  frontend/src/hooks/useCalendar.ts
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#98 [FE] 일정 관련 msw 핸들러 작성
  frontend/src/mocks/fixtures/schedules.ts
  frontend/src/mocks/handlers/calendar.ts
Labels: 💻 프론트엔드, 🤖 테스트

#104 [BE] 백엔드 CI 워크플로우 생성
  .github/workflows/backend-ci.yml
Labels: 🍃 백엔드, ⚙️ 환경설정

#105 [BE] dev브랜치 머지시 빌드 & artifact 업로드 깃헙플로우 추가
  .github/workflows/backend-dev-branch-build-and-upload.yml
Labels: 🍃 백엔드, ⚙️ 환경설정

#94 [BE] 일정 수정 기능 구현
  backend/src/docs/asciidoc/schedule.adoc
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleUpdateRequest.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Span.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Title.java
  backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleException.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamPlaceScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/fixtures/ScheduleFixtures.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/ScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepositoryTest.java
Labels: 🍃 백엔드, 💡 기능, 📑 문서

#87 [BE] 일정 삭제 기능
  backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamPlaceScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/ScheduleRepositoryTest.java
Labels: 🍃 백엔드, 💡 기능

#116 [FE] schedule bar 렌더링 구현
  frontend/src/App.tsx
  frontend/src/components/Calendar/Calendar.stories.tsx
  frontend/src/components/Calendar/Calendar.styled.ts
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
  frontend/src/constants/calendar.ts
  frontend/src/mocks/fixtures/schedules.ts
  frontend/src/utils/generateScheduleBars.ts
Labels: 💻 프론트엔드, 💡 기능

#118 [FE] Tanstack query 설치 및 Fetch API 추상화
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/fetch.ts
  frontend/src/apis/http.ts
  frontend/src/apis/schedule.ts
  frontend/src/hooks/queries/useSchedules.ts
  frontend/src/index.tsx
Labels: 💻 프론트엔드, 💡 기능

#120 [FE] webpack 환경변수관련 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.js
Labels: 💻 프론트엔드, ⚙️ 환경설정

#124 [BE] cd 워크플로우 작성
  .github/workflows/backend-dev-branch-build-and-upload.yml
Labels: 🍃 백엔드, ⚙️ 환경설정

#126 [BE] dev DB 관련 설정
  backend/.gitignore
  backend/build.gradle
Labels: 🍃 백엔드, ⚙️ 환경설정

#123 [FE] 캘린더 바 버그 수정 및 안정성 개선
  frontend/src/utils/generateScheduleBars.ts
Labels: 🚨 버그, 💻 프론트엔드, 💡 기능

#128 [FE] http 추상화 로직 수정 및 에러 throw 로직 추가
  frontend/src/apis/http.ts
Labels: 🚨 버그, 💻 프론트엔드

#131 [FE] 캘린더 페이지 구현
  frontend/src/App.tsx
  frontend/src/apis/http.ts
  frontend/src/apis/schedule.ts
  frontend/src/assets/svg/arrow-left.svg
  frontend/src/assets/svg/arrow-right.svg
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/logo.svg
  frontend/src/assets/svg/plus.svg
  frontend/src/components/Calendar/Calendar.styled.ts
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/Calendar/DateCell/DateCell.styled.ts
  frontend/src/components/Calendar/DateCell/DateCell.tsx
  frontend/src/components/IntegratedCalendar/IntegratedCalendar.stories.tsx
  frontend/src/components/IntegratedCalendar/IntegratedCalendar.styled.ts
  frontend/src/components/IntegratedCalendar/IntegratedCalendar.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.styled.ts
  frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.tsx
  frontend/src/constants/calendar.ts
  frontend/src/hooks/queries/useSendSchedule.ts
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/index.tsx
  frontend/src/types/size.ts
Labels: 💻 프론트엔드, 💡 기능

#132 [FE] ScheduleBar 스타일 수정
  frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
  frontend/src/utils/generateScheduleBars.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#129 [FE] 일정 조회, 삭제 api 연결
  frontend/src/apis/schedule.ts
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
  frontend/src/components/ScheduleModal/ScheduleModal.stories.tsx
  frontend/src/components/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/ScheduleModal/ScheduleModal.tsx
  frontend/src/hooks/queries/useDeleteSchedule.ts
  frontend/src/hooks/queries/useFetchScheduleById.ts
  frontend/src/hooks/queries/useFetchSchedules.ts
  frontend/src/hooks/schedule/useScheduleModal.ts
  frontend/src/mocks/fixtures/schedules.ts
  frontend/src/types/schedule.ts
  frontend/src/utils/formatDateTime.ts
  frontend/src/utils/generateScheduleBars.ts
Labels: 💻 프론트엔드, 💡 기능

#135 [BE] CD yml Syntax Error 수정
  .github/workflows/backend-dev-branch-build-and-upload.yml
Labels: 🍃 백엔드, ⚙️ 환경설정

#138 [BE] ci cd workflow 수정
  .github/workflows/backend-ci.yml
  .github/workflows/backend-dev-branch-build-and-upload.yml
Labels: 🍃 백엔드, ⚙️ 환경설정

#142 [FE] crypto.randomUUID를 대체하는 유틸함수 작성
  frontend/src/utils/generateScheduleBars.ts
  frontend/src/utils/generateUuid.ts
Labels: 🚨 버그, 💻 프론트엔드

#130 [BE] Teamplace 참가 여부를 확인하는 TeamPlaceInterceptor 구현
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Email.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/configuration/TeamPlaceInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceException.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/ScheduleApiDocsTest.java
Labels: 🍃 백엔드, 💡 기능

#143 [BE] 통합 캘린더 일정 조회 기능 구현
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/ScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleWithTeamPlaceIdResponse.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/SchedulesWithTeamPlaceIdResponse.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/MyCalendarScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/ScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/ScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/ScheduleRepositoryTest.java
  backend/src/test/resources/h2-data.sql
Labels: 🍃 백엔드, 💡 기능

#161 [FE] QueryClientProvider를 사용해서 컴포넌트가 스토리북에 제대로 보여지지 않는 문제 해결
  frontend/.storybook/preview.tsx
Labels: 💻 프론트엔드, 🤖 테스트

#149 [BE] 배포시 배포용 application.yml 파일 artifact 노출 문제 해결
  .github/workflows/backend-dev-branch-build-and-upload.yml
Labels: 🍃 백엔드, ⚙️ 환경설정

#165 [BE] 개발 서버 배포 자동화 버튼 제거
  .github/workflows/backend-dev-branch-build-and-upload.yml
Labels: 🍃 백엔드, ⚙️ 환경설정

#163 [FE] 캘린더 관련 코드 일부 리팩토링
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
  frontend/src/components/ScheduleModal/ScheduleModal.tsx
  frontend/src/hooks/queries/useDeleteSchedule.ts
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/hooks/schedule/useScheduleEditModal.ts
  frontend/src/hooks/useCalendar.ts
  frontend/src/types/typeGuard.ts
  frontend/src/utils/formatISOString.test.ts
  frontend/src/utils/formatISOString.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#148 [FE] 하루 스케줄이 3개 초과일 때 보여줄 더보기 컴포넌트 구현
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/IntegratedCalendar/IntegratedCalendar.stories.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/ScheduleEditModal/ScheduleEditModal.stories.tsx
  frontend/src/components/ScheduleModal/ScheduleModal.stories.tsx
  frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.stories.ts
  frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.styled.ts
  frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.tsx
  frontend/src/components/common/Header/Header.stories.tsx
Labels: 💻 프론트엔드, 💡 기능

#153 [FE] 하루 일정 모달 구현
  frontend/src/apis/schedule.ts
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/Calendar/DateCell/DateCell.styled.ts
  frontend/src/components/Calendar/DateCell/DateCell.tsx
  frontend/src/components/DailyScheduleModal/DailyScheduleModal.stories.tsx
  frontend/src/components/DailyScheduleModal/DailyScheduleModal.styled.ts
  frontend/src/components/DailyScheduleModal/DailyScheduleModal.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
  frontend/src/constants/calendar.ts
  frontend/src/hooks/queries/useFetchDailySchedules.ts
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#156 [BE] 팀 캘린더 하루 일정 조회 구현
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleResponse.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/SchedulesResponse.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/MyCalendarScheduleController.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamCalendarScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/MyCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/ScheduleRepositoryTest.java
Labels: 🍃 백엔드, 💡 기능

#174 [BE] 2차 스프린트 이후 수정할 것 리팩토링
  backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Email.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/ProfileImageUrl.java
  backend/src/main/java/team/teamby/teambyteam/member/exception/MemberException.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleResponse.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleWithTeamPlaceIdResponse.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/vo/Span.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/vo/Title.java
  backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/configuration/TeamPlaceInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/vo/Name.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceException.java
  backend/src/test/java/team/teamby/teambyteam/common/AcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/common/RepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/common/ServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/fixtures/ScheduleFixtures.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/NameTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/ScheduleRepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/SpanTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/TitleTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/NameTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepositoryTest.java
  backend/src/test/resources/h2-truncate.sql
Labels: 🍃 백엔드, 🔨 리팩터링

#192 [FE] 공통 menu 컴포넌트 구현
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/Menu/Menu.stories.tsx
  frontend/src/components/common/Menu/Menu.styled.ts
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/hooks/useClickOutside.ts
  frontend/src/hooks/useKeydownEffect.ts
Labels: 💻 프론트엔드, 💡 기능

#201 [BE] 팀 피드 엔티티 구현
  backend/src/main/java/team/teamby/teambyteam/feed/domain/Feed.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedRepository.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedThread.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedType.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/Notification.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/ScheduleNotification.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/vo/Content.java
  backend/src/main/java/team/teamby/teambyteam/feed/exception/FeedException.java
  backend/src/test/java/team/teamby/teambyteam/feed/domain/FeedRepositoryTest.java
Labels: 🍃 백엔드, 💡 기능

#203 [FE] 프론트엔드 CD workflow 작성
  .github/workflows/frontend-cd.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/http.ts
  frontend/webpack.config.js
Labels: 🚨 버그, 💻 프론트엔드, ⚙️ 환경설정

#193 [FE] 좌표 날짜 변환 유틸함수 구현
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/hooks/queries/useFetchDailySchedules.ts
  frontend/src/hooks/queries/useFetchSchedules.ts
  frontend/src/utils/getDateByPosition.test.ts
  frontend/src/utils/getDateByPosition.ts
Labels: 💻 프론트엔드, 💡 기능

#209 [BE] 단일 일정 api url 변경
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamCalendarScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
Labels: 🚨 버그, 🍃 백엔드

#225 [BE] 존재하는 모든 테스트 data.sql 의존성 제거
  backend/src/test/java/team/teamby/teambyteam/common/AcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/common/RepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/common/ServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/BuilderSupporter.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/MemberFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/MemberTeamPlaceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/ScheduleFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/TeamPlaceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MyCalendarScheduleAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamCalendarScheduleAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/MyCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/ScheduleRepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceRepositoryTest.java
  backend/src/test/resources/h2-data.sql
  backend/src/test/resources/h2-reset-pk.sql
Labels: 🍃 백엔드, 🔨 리팩터링, 🤖 테스트

#200 [BE] member interceptor경로설정,인증예외설정
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
Labels: 🍃 백엔드, 💡 기능

#227 [BE] 팀플레이스 일정 서비스에서 사용하지 않는 필드 제거
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
Labels: 🍃 백엔드, 🔨 리팩터링

#206 [FE] 일정더보기와 하루일정모달 연결
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.tsx
Labels: 💻 프론트엔드, 💡 기능

#205 [FE] 팀 피드 일정 알림 컴포넌트 UI 구현
  frontend/src/components/Notification/Notification.stories.ts
  frontend/src/components/Notification/Notification.styled.ts
  frontend/src/components/Notification/Notification.tsx
  frontend/src/types/size.ts
Labels: 💻 프론트엔드, 💡 기능

#159 [BE] jwt token 생성, 검증, email 추출 기능 구현
  backend/src/main/java/team/teamby/teambyteam/auth/exception/AuthenticationException.java
  backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenExtractor.java
  backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenProvider.java
  backend/src/main/java/team/teamby/teambyteam/auth/presentation/MemberInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/auth/presentation/TeamPlaceInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/member/exception/MemberException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/configuration/TeamPlaceInterceptor.java
  backend/src/test/java/team/teamby/teambyteam/common/AcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MyCalendarScheduleAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamCalendarScheduleAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/MyCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
  backend/src/test/resources/application.yml
Labels: 🍃 백엔드, 💡 기능

#222 [FE]팀 피드 스레드 컴포넌트 UI 구현
  frontend/src/components/Thread/Thread.stories.ts
  frontend/src/components/Thread/Thread.styled.ts
  frontend/src/components/Thread/Thread.tsx
  frontend/src/types/size.ts
  frontend/src/utils/formatDateTime.test.ts
  frontend/src/utils/formatWriteTime.test.ts
  frontend/src/utils/formatWriteTime.ts
Labels: 💻 프론트엔드, 💡 기능

#236 [FE] 사용하지 않는 파일 삭제 및 사소한 코드 정리
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/DailyScheduleModal/DailyScheduleModal.stories.tsx
  frontend/src/components/DateCell/DateCell.stories.tsx
  frontend/src/components/DateCell/DateCell.styled.ts
  frontend/src/components/DateCell/DateCell.tsx
  frontend/src/components/IntegratedCalendar/IntegratedCalendar.tsx
  frontend/src/components/common/Button/Button.styled.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Input/Input.styled.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Text/Text.styled.ts
  frontend/src/components/common/Text/Text.tsx
  frontend/src/stories/Button.stories.ts
  frontend/src/stories/Button.tsx
  frontend/src/stories/Header.stories.ts
  frontend/src/stories/Header.tsx
  frontend/src/stories/Introduction.mdx
  frontend/src/stories/Page.stories.ts
  frontend/src/stories/Page.tsx
  frontend/src/stories/assets/code-brackets.svg
  frontend/src/stories/assets/colors.svg
  frontend/src/stories/assets/comments.svg
  frontend/src/stories/assets/direction.svg
  frontend/src/stories/assets/flow.svg
  frontend/src/stories/assets/plugin.svg
  frontend/src/stories/assets/repo.svg
  frontend/src/stories/assets/stackalt.svg
  frontend/src/stories/button.css
  frontend/src/stories/header.css
  frontend/src/stories/page.css
Labels: 💻 프론트엔드, 🔨 리팩터링

#235 [FE] Query key에 teamPlaceId 추가
  frontend/src/components/ScheduleModal/ScheduleModal.tsx
  frontend/src/hooks/queries/useDeleteSchedule.ts
  frontend/src/hooks/queries/useFetchScheduleById.ts
  frontend/src/hooks/queries/useFetchSchedules.ts
  frontend/src/hooks/queries/useModifySchedule.ts
  frontend/src/hooks/queries/useSendSchedule.ts
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/hooks/schedule/useScheduleEditModal.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#233 [BE] 일정 수정 & 삭제 시 해당 팀플레이스의 일정인지 검증 로직 추가
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
Labels: 🍃 백엔드, 💡 기능

#234 [BE] 피드 스레드 등록 기능 구현
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedThreadWritingRequest.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/vo/Content.java
  backend/src/main/java/team/teamby/teambyteam/feed/presentation/FeedThreadController.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/IdOnly.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberRepository.java
  backend/src/main/resources/application.yml
  backend/src/test/java/team/teamby/teambyteam/common/ServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/BuilderSupporter.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/FeedThreadFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/FeedThreadAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/fixtures/ScheduleFixtures.java
Labels: 🍃 백엔드, 💡 기능

#208 [FE] 공통 Menu 컴포넌트 재사용성 개선
  frontend/src/components/common/Menu/Menu.stories.tsx
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/common/Menu/MenuButton/MenuButton.tsx
  frontend/src/components/common/Menu/MenuContext.tsx
  frontend/src/components/common/Menu/MenuItem/MenuItem.styled.ts
  frontend/src/components/common/Menu/MenuItem/MenuItem.tsx
  frontend/src/components/common/Menu/MenuList/MenuList.styled.ts
  frontend/src/components/common/Menu/MenuList/MenuList.tsx
  frontend/src/hooks/useMenu.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#232 [BE] 팀 캘린더 하루 일정 조회 로직 리팩토링
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/CalendarPeriod.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/ScheduleFixtures.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/ScheduleRepositoryTest.java
Labels: 🍃 백엔드, 🔨 리팩터링

#239 [BE] Member, MemberTeamPlace, TeamPlace 구조 및 연관관계 리팩터링
  backend/src/main/java/team/teamby/teambyteam/auth/presentation/TeamPlaceParticipationInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberIdAndDisplayNameOnly.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberName.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/DisplayTeamPlaceName.java
  backend/src/main/java/team/teamby/teambyteam/member/exception/MemberTeamPlaceException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberNameTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayTeamPlaceNameTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 💡 기능

#243 [FE] 공통 체크박스 컴포넌트 구현
  frontend/src/assets/svg/check.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/common/Checkbox/Checkbox.stories.tsx
  frontend/src/components/common/Checkbox/Checkbox.styled.ts
  frontend/src/components/common/Checkbox/Checkbox.tsx
  frontend/src/types/size.ts
Labels: 💻 프론트엔드, 💡 기능

#242 [FE] MenuItem의 css prop optional로 수정
  frontend/src/components/common/Menu/MenuItem/MenuItem.tsx
Labels: 🚨 버그, 💻 프론트엔드

#241 [FE] 팀피드 스레드 조회 api 연결
  frontend/src/apis/feed.ts
  frontend/src/components/ThreadList/ThreadList.stories.ts
  frontend/src/components/ThreadList/ThreadList.styled.ts
  frontend/src/components/ThreadList/ThreadList.tsx
  frontend/src/constants/feed.ts
  frontend/src/hooks/queries/useFetchThreads.ts
  frontend/src/hooks/useIntersectionObserver.ts
  frontend/src/mocks/fixtures/threads.ts
  frontend/src/mocks/handlers/feed.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/types/feed.ts
Labels: 💻 프론트엔드, 💡 기능

#245 [FE] 일정 등록 모달 기본 날짜 변경
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/hooks/useCalendar.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#249 [BE] Truncate 리팩토링
  backend/src/test/resources/h2-truncate.sql
Labels: 🍃 백엔드, 🔨 리팩터링

#238 [BE] 공지 등록 기능 구현
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeRegisterRequest.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/NoticeRepository.java
  backend/src/main/java/team/teamby/teambyteam/notice/exception/NoticeException.java
  backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/BuilderSupporter.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/MemberFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/NoticeFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/NoticeAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/domain/NoticeRepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/domain/vo/ContentTest.java
Labels: 🍃 백엔드, 💡 기능
