Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2023-11, with the labels that each got.

#847 [BE] SSE 연결시 케시전송 제거 및 Keep-Alive 설정 추가
  backend/src/main/java/team/teamby/teambyteam/sse/application/SseSubscribeService.java
  backend/src/main/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisher.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java
  backend/src/main/java/team/teamby/teambyteam/sse/presentation/SseController.java
  backend/src/test/java/team/teamby/teambyteam/icalendar/acceptance/IcalendarAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/application/SseSubscribeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepositoryTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-상

#844 [FE] 컨벤션에 맞게 리팩터링
  frontend/package-lock.json
  frontend/src/apis/feed.ts
  frontend/src/components/common/Menu/MenuList/MenuList.tsx
  frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
  frontend/src/components/team/TeamExitModal/TeamExitModal.tsx
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/hooks/schedule/useScheduleEditModal.ts
  frontend/src/hooks/team/useTeamExitModal.ts
  frontend/src/hooks/team/useTeamPlaceInfoModal.ts
  frontend/src/hooks/thread/useImageUpload.tsx
  frontend/src/hooks/thread/useTeamFeedPage.ts
  frontend/src/hooks/useBottomSheet.ts
  frontend/src/hooks/useCalendar.ts
  frontend/src/hooks/useClickOutside.ts
  frontend/src/hooks/user/useUserInfoModal.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#833 [FE] 팀 정보 아이콘 접근 시 prefetching 적용
  frontend/src/components/common/Header/Header.tsx
Labels: 💻 프론트엔드, 💡 기능

#854 [BE] 피드작성 이벤트에 작성된 피드 내용 포함
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/event/FeedEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceConnectedEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterId.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceSseEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/presentation/SseController.java
  backend/src/test/java/team/teamby/teambyteam/sse/TestEvent.java
Labels: 🍃 백엔드, 🔨 리팩터링, 💡 기능, 중요도-상

#851 [FE] 내 일정 캘린더에 Prefetching 적용
  frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
  frontend/src/hooks/queries/usePrefetchMySchedules.ts
Labels: 💻 프론트엔드, 💡 기능

#853 [FE] useSSE를 ProtectRoute에서 호출하도록 수정
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/hooks/queries/useSSE.ts
  frontend/src/index.tsx
  frontend/src/pages/PageTemplate/PageTemplate.tsx
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 🚨 버그, 💻 프론트엔드

#845 [FE] 팀바팀 모바일 버전 구현
  frontend/src/App.tsx
  frontend/src/components/common/Error404/Error404.styled.ts
  frontend/src/components/common/Error404/Error404.tsx
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
  frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
  frontend/src/components/link/LinkTable/LinkTable.styled.ts
  frontend/src/components/link/LinkTable/LinkTable.tsx
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.styled.ts
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.tsx
  frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
  frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.styled.ts
  frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.tsx
  frontend/src/components/user/ServiceCenterModal/ServiceCenterModal.tsx
  frontend/src/constants/toast.ts
  frontend/src/hooks/thread/useThreadHeight.ts
  frontend/src/mobilePages/M_LandingPage/M_LandingPage.styled.ts
  frontend/src/mobilePages/M_LandingPage/M_LandingPage.tsx
  frontend/src/mobilePages/M_PageTemplate/M_PageTemplate.styled.ts
  frontend/src/mobilePages/M_PageTemplate/M_PageTemplate.tsx
  frontend/src/mobilePages/M_TeamSelectPage/M_TeamSelectPage.styled.ts
  frontend/src/mobilePages/M_TeamSelectPage/M_TeamSelectPage.tsx
  frontend/src/mocks/fixtures/schedules.ts
  frontend/src/mocks/handlers/feed.ts
  frontend/src/pages/CreatePage/CreatePage.styled.ts
  frontend/src/pages/CreatePage/CreatePage.tsx
  frontend/src/pages/Error404Page/Error404Page.tsx
  frontend/src/pages/JoinPage/JoinPage.styled.ts
  frontend/src/pages/JoinPage/JoinPage.tsx
  frontend/src/pages/StartPage/StartPage.styled.ts
  frontend/src/pages/StartPage/StartPage.tsx
  frontend/src/pages/TeamCalendarPage/TeamCalendarPage.tsx
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
  frontend/src/styles/theme.ts
  frontend/src/utils/getIsMobile.ts
Labels: 💻 프론트엔드, 💡 기능

#849 [FE] 프로필 닉네임 수정 낙관적 업데이트 적용
  frontend/src/hooks/queries/useModifyUserInfo.ts
  frontend/src/hooks/user/useUserInfoModal.ts
Labels: 💻 프론트엔드, 💡 기능

#835 [FE] 이미지 모달의 이미지 전환을 키보드 조작으로 할 수 있도록 개선
  frontend/src/components/feed/Carousel/Carousel.styled.ts
  frontend/src/components/feed/Carousel/Carousel.tsx
  frontend/src/components/feed/ThreadImageModal/ThreadImageModal.tsx
  frontend/src/hooks/thread/useCarouselPageNo.ts
Labels: 💻 프론트엔드, 💡 기능

#862 [BE] 피드조회시 쿼리 최적화
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedRepository.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedThread.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/Notice.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-중

#860 [BE] SSE 관련 기능들 리팩터링 및 멀티스레드 제거
  backend/src/main/java/team/teamby/teambyteam/sse/application/SseSubscribeService.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java
  backend/src/test/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisherTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-하

#861 [BE] 일정변동이 잦은 경우 ics배포
  backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListener.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishService.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/application/PeriodicIcalendarPublishService.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/domain/IcalendarPublishCounter.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/domain/PublishedIcalendarRepository.java
  backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListenerTest.java
  backend/src/test/java/team/teamby/teambyteam/icalendar/domain/IcalendarPublishCounterTest.java
Labels: 🍃 백엔드, 💡 기능, 중요도-상

#865 [FE] console.log 추가
  frontend/src/hooks/queries/useSSE.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#867 [FE] 콘솔 출력 데이터 형태 변경
  frontend/src/hooks/queries/useSSE.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#869 [FE] 데이터 타입 확인
  frontend/src/hooks/queries/useSSE.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#870 [FE] sse data 콘솔 수정
  frontend/src/hooks/queries/useSSE.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#871 [FE] teamPlace 전환시 SSE 끊고 다시 연결하기
  frontend/src/hooks/queries/useSSE.ts
  frontend/src/pages/PageTemplate/PageTemplate.tsx
Labels: 🚨 버그, 💻 프론트엔드

#872 [FE]팀플레이스 전환시 sse 에서 teamPlaceId console
  frontend/src/hooks/queries/useSSE.ts
  frontend/src/mobilePages/M_PageTemplate/M_PageTemplate.tsx
Labels: 🚨 버그, 💻 프론트엔드

#873 [FE]아이디 비교 로직 추가
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#874 [FE] SSE 연결을 useCallback로 감싸 한번만 작동하도록 변경
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#875 [FE] SSE 중복 연결 버그 픽스
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드
