Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2023-08, with the labels that each got.

#246 [FE] 팀피드 스레드 작성 바텀시트 구현
  frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.stories.tsx
  frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
  frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
  frontend/src/hooks/useBottomSheet.ts
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#250 [BE] 통합 캘린더 하루 일정 조회 기능 구현
  backend/src/main/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/MyCalendarScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/ScheduleFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MyCalendarScheduleAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/MyCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleServiceTest.java
Labels: 🍃 백엔드, 💡 기능

#244 [FE] 공지 스레드 컴포넌트 구현
  frontend/src/assets/png/index.ts
  frontend/src/assets/png/notice-thread-background.png
  frontend/src/assets/svg/arrow-expand-less.svg
  frontend/src/assets/svg/arrow-expand-more.svg
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/megaphone.svg
  frontend/src/components/ExpandButton/ExpandButton.stories.tsx
  frontend/src/components/ExpandButton/ExpandButton.styled.ts
  frontend/src/components/ExpandButton/ExpandButton.tsx
  frontend/src/components/NoticeThread/NoticeTag/NoticeTag.stories.tsx
  frontend/src/components/NoticeThread/NoticeTag/NoticeTag.styled.ts
  frontend/src/components/NoticeThread/NoticeTag/NoticeTag.tsx
  frontend/src/components/NoticeThread/NoticeThread.stories.tsx
  frontend/src/components/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/NoticeThread/NoticeThread.tsx
  frontend/src/constants/feed.ts
  frontend/src/hooks/thread/useThreadHeight.tsx
  frontend/src/types/assets.d.ts
  frontend/src/types/size.ts
Labels: 💻 프론트엔드, 💡 기능

#257 [FE]통합캘린더 나의 하루일정 보기 UI 구현
  frontend/src/assets/svg/clock.svg
  frontend/src/assets/svg/group.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/IntegratedDailySchedule/IntegratedDailySchedule.stories.ts
  frontend/src/components/IntegratedDailySchedule/IntegratedDailySchedule.styled.ts
  frontend/src/components/IntegratedDailySchedule/IntegratedDailySchedule.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/team.ts
  frontend/src/utils/formatTime.test.ts
  frontend/src/utils/formatTime.ts
Labels: 💻 프론트엔드, 💡 기능

#265 [FE] teamColor 충돌 해결
  frontend/src/styles/theme.ts
Labels: 🚨 버그, 💻 프론트엔드

#252 [FE] 일정 등록 종일 기능 구현
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.styled.ts
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/common/Menu/Menu.stories.tsx
  frontend/src/components/common/Menu/Menu.styled.ts
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/common/Menu/MenuButton/MenuButton.tsx
  frontend/src/components/common/Menu/MenuContext.tsx
  frontend/src/components/common/Menu/MenuItem/MenuItem.styled.ts
  frontend/src/components/common/Menu/MenuItem/MenuItem.tsx
  frontend/src/components/common/Menu/MenuList/MenuList.styled.ts
  frontend/src/components/common/Menu/MenuList/MenuList.tsx
  frontend/src/constants/calendar.ts
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/styles/theme.ts
  frontend/src/types/typeGuard.ts
Labels: 💻 프론트엔드, 💡 기능

#266 [FE] 제거된 함수 import 문 제거
  frontend/src/hooks/schedule/useScheduleAddModal.ts
Labels: 🚨 버그, 💻 프론트엔드

#268 [FE] 빌드 실패 시 action이 실패하도록 CI 스크립트 수정
  .github/workflows/frontend-ci.yml
Labels: 💻 프론트엔드, 🔨 리팩터링, ⚙️ 환경설정

#264 [FE] 일정 상세보기 모달 아이콘 디자인 수정
  frontend/src/assets/svg/close.svg
  frontend/src/assets/svg/delete.svg
  frontend/src/assets/svg/edit.svg
  frontend/src/components/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/ScheduleModal/ScheduleModal.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#271 [FE] 디자인 깨지는 현상 수정
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/ScheduleModal/ScheduleModal.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#269 [FE] 통합 캘린더 스케줄 서클 구현을 위한 유틸 함수 작성
  frontend/src/constants/calendar.ts
  frontend/src/types/schedule.ts
  frontend/src/utils/generateScheduleCirclesMatrix.test.ts
  frontend/src/utils/generateScheduleCirclesMatrix.ts
Labels: 💻 프론트엔드, 💡 기능

#260 [FE] 공통 Toast 컴포넌트 작성
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/Toast.styled.ts
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/components/common/Toast/ToastContext.tsx
  frontend/src/components/common/Toast/ToastList.styled.ts
  frontend/src/components/common/Toast/ToastList.tsx
  frontend/src/constants/toast.ts
  frontend/src/hooks/useToast.ts
  frontend/src/index.tsx
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#276 [FE] 팀피드 공지 조회 API 연결
  frontend/src/apis/feed.ts
  frontend/src/components/ThreadList/ThreadList.tsx
  frontend/src/hooks/queries/useFetchNoticeThread.ts
  frontend/src/mocks/fixtures/threads.ts
  frontend/src/mocks/handlers/feed.ts
  frontend/src/types/feed.ts
Labels: 💻 프론트엔드, 💡 기능

#278 [FE] 일정 수정 종일/시간대 선택 구현
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/ScheduleEditModal/ScheduleEditModal.styled.ts
  frontend/src/components/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/TimeTableMenu/TimeTableMenu.stories.tsx
  frontend/src/components/TimeTableMenu/TimeTableMenu.styled.ts
  frontend/src/components/TimeTableMenu/TimeTableMenu.tsx
  frontend/src/components/common/Menu/Menu.stories.tsx
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/hooks/schedule/useScheduleEditModal.ts
Labels: 💻 프론트엔드, 🔨 리팩터링, 💡 기능

#281 [BE] 구글 OAuth 로그인 기능 추가
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/dto/GoogleTokenResponse.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/dto/OAuthMember.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/dto/TokenResponse.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/client/GoogleOAuthClient.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/client/OAuthClient.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/config/GoogleOAuthProperties.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/util/GoogleOAuthUriGenerator.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/util/OAuthUriGenerator.java
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/resources/application.yml
  backend/src/test/resources/application.yml
Labels: 🍃 백엔드, 💡 기능

#279 [FE]통합캘린더 스케줄 렌더링
  frontend/src/components/MyCalendar/MyCalendar.styled.ts
  frontend/src/components/MyCalendar/MyCalendar.tsx
  frontend/src/components/common/TeamBadge/TeamBadge.styled.ts
  frontend/src/hooks/queries/useDeleteSchedule.ts
  frontend/src/hooks/queries/useModifySchedule.ts
  frontend/src/hooks/queries/useSendSchedule.ts
  frontend/src/mocks/handlers/calendar.ts
Labels: 💻 프론트엔드, 💡 기능

#282 [FE] 일정 등록, 수정, 삭제 성공 시 Toast를 보여주는 로직 추가
  frontend/src/components/ScheduleModal/ScheduleModal.tsx
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/hooks/schedule/useScheduleEditModal.ts
Labels: 💻 프론트엔드, 💡 기능

#280 [FE] 팀 피드, 공지 작성 api 연결
  frontend/.storybook/preview.tsx
  frontend/src/apis/feed.ts
  frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.stories.tsx
  frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
  frontend/src/hooks/queries/useSendNoticeThread.ts
  frontend/src/hooks/queries/useSendThread.ts
  frontend/src/hooks/thread/useThreadAddBottomSheet.ts
  frontend/src/mocks/handlers/feed.ts
  frontend/src/types/feed.ts
Labels: 💻 프론트엔드, 💡 기능

#286 [FE] 스케줄바 타이틀 표시 구현
  frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
Labels: 💻 프론트엔드, 💡 기능

#292 [FE] 네비게이션바 UI 구현
  frontend/src/assets/svg/calendar.svg
  frontend/src/assets/svg/feed.svg
  frontend/src/assets/svg/home.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/common/NavigationBar/NavigationBar.stories.ts
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
Labels: 💻 프론트엔드, 💡 기능

#288 [FE]통합 일정 사이드바 구현
  frontend/src/components/MyCalendar/MyCalendar.styled.ts
  frontend/src/components/MyCalendar/MyCalendar.tsx
  frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.styled.ts
  frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.tsx
  frontend/src/components/common/SideBar/SideBar.stories.ts
  frontend/src/components/common/SideBar/SideBar.styled.ts
  frontend/src/components/common/SideBar/SideBar.tsx
  frontend/src/mocks/fixtures/schedules.ts
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#294 [FE] 스케줄 바에 schedule prop 추가 및 유틸함수 리팩터링
  frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
  frontend/src/utils/generateScheduleBars.test.ts
  frontend/src/utils/generateScheduleBars.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#283 [FE] 팀 정보를 조회해오는 API 로직 구현
  frontend/src/apis/team.ts
  frontend/src/hooks/queries/useFetchTeamPlaces.ts
  frontend/src/mocks/fixtures/team.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/team.ts
  frontend/src/types/team.ts
Labels: 💻 프론트엔드, 💡 기능, 🤖 테스트

#251 [BE] 팀피드 스레드 조회 기능 구현
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedsResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/Feed.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedRepository.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedThread.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/ScheduleNotification.java
  backend/src/main/java/team/teamby/teambyteam/feed/presentation/FeedThreadController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/FeedThreadAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/domain/FeedRepositoryTest.java
Labels: 🍃 백엔드, 💡 기능

#296 [FE]페이지 템플릿 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/components/Calendar/Calendar.styled.ts
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/MyCalendar/MyCalendar.styled.ts
  frontend/src/components/MyCalendar/MyCalendar.tsx
  frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.styled.ts
  frontend/src/components/common/SideBar/SideBar.styled.ts
  frontend/src/components/common/SideBar/SideBar.tsx
  frontend/src/components/pages/PageTemplate/PageTemplate.styled.ts
  frontend/src/components/pages/PageTemplate/PageTemplate.tsx
  frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.styled.ts
  frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#299 [BE] fix: response 오타 수정
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleWithTeamPlaceIdResponse.java
Labels: 🚨 버그, 🍃 백엔드

#304 [FE] 스레드 페이지 구현
  frontend/src/assets/svg/arrow-up.svg
  frontend/src/assets/svg/calendar.svg
  frontend/src/assets/svg/drive.svg
  frontend/src/assets/svg/feed.svg
  frontend/src/assets/svg/home.svg
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/write.svg
  frontend/src/components/NoticeThread/NoticeThread.stories.tsx
  frontend/src/components/NoticeThread/NoticeThread.tsx
  frontend/src/components/Notification/Notification.styled.ts
  frontend/src/components/Notification/Notification.tsx
  frontend/src/components/Thread/Thread.styled.ts
  frontend/src/components/Thread/Thread.tsx
  frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
  frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
  frontend/src/components/ThreadList/ThreadList.styled.ts
  frontend/src/components/ThreadList/ThreadList.tsx
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/common/SideBar/SideBar.styled.ts
  frontend/src/components/pages/FeedPage/FeedPage.styled.ts
  frontend/src/components/pages/FeedPage/FeedPage.tsx
  frontend/src/components/pages/PageTemplate/PageTemplate.styled.ts
  frontend/src/index.tsx
  frontend/webpack.config.js
Labels: 💻 프론트엔드, 💡 기능

#297 [FE] 스케줄바 다음주로 넘어갈 때 끊기는 디자인 수정
  frontend/src/assets/svg/double-arrow-right.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
  frontend/src/utils/generateScheduleBars.test.ts
  frontend/src/utils/generateScheduleBars.ts
Labels: 💻 프론트엔드, 💡 기능

#305 [FE]사이드 바 팀플레이스 조회 로직 연결
  frontend/src/components/MyCalendar/MyCalendar.stories.tsx
  frontend/src/components/MyCalendar/MyCalendar.tsx
  frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.stories.ts
  frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.tsx
  frontend/src/components/common/SideBar/SideBar.tsx
  frontend/src/hooks/queries/useFetchTeamPlaces.ts
  frontend/src/utils/getInfoByTeamPlaceId.ts
Labels: 💻 프론트엔드, 💡 기능

#309 [BE] 스레드 조회 타입 수정
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedType.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/ScheduleNotification.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/NotificationServiceTest.java
Labels: 🚨 버그, 🍃 백엔드

#312 [BE] 소속 팀플레이스인지 확인할 수 없는 버그 fix
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
Labels: 🚨 버그, 🍃 백엔드

#298 [BE] 공지 조회 기능 구현
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeResponse.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/NoticeRepository.java
  backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/NoticeFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/NoticeAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/domain/NoticeRepositoryTest.java
Labels: 🍃 백엔드, 💡 기능

#301 [BE] 사용자가 속한 팀플레이스들 목록 조회 기능 구현
  backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
  backend/src/main/java/team/teamby/teambyteam/member/application/dto/TeamPlaceResponse.java
  backend/src/main/java/team/teamby/teambyteam/member/application/dto/TeamPlacesResponse.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/TeamPlaceColor.java
  backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/TeamPlaceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTest.java
Labels: 🍃 백엔드, 💡 기능

#315 [FE] 팀플레이스 색상과 조회 로직 연결
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/MyCalendar/MyCalendar.stories.tsx
  frontend/src/components/MyCalendar/MyCalendar.tsx
  frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.stories.ts
  frontend/src/components/MyDailyScheduleList/MyDailyScheduleList.tsx
  frontend/src/components/Notification/Notification.stories.ts
  frontend/src/components/Notification/Notification.styled.ts
  frontend/src/components/Notification/Notification.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.stories.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
  frontend/src/components/ScheduleEditModal/ScheduleEditModal.stories.tsx
  frontend/src/components/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/ScheduleMoreCell/ScheduleMoreCell.styled.ts
  frontend/src/components/ThreadList/ThreadList.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/SideBar/SideBar.tsx
  frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.styled.ts
  frontend/src/components/pages/TeamCalendarPage/TeamCalendarPage.tsx
  frontend/src/contexts/TeamPlaceContext.tsx
  frontend/src/hooks/useTeamPlace.ts
  frontend/src/index.tsx
  frontend/src/types/schedule.ts
  frontend/src/utils/generateScheduleBars.test.ts
  frontend/src/utils/generateScheduleBars.ts
  frontend/src/utils/getInfoByTeamPlaceId.ts
Labels: 💻 프론트엔드, 💡 기능

#313 [FE] 스케줄 서클 유틸함수 중복반환 해결
  frontend/src/utils/generateScheduleCirclesMatrix.test.ts
  frontend/src/utils/generateScheduleCirclesMatrix.ts
Labels: 🚨 버그, 💻 프론트엔드

#314 [FE] Notification 디자인 수정
  frontend/src/components/Notification/Notification.stories.ts
  frontend/src/components/Notification/Notification.styled.ts
  frontend/src/components/Notification/Notification.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#319 [FE] Notification이 보이지 않는 현상 수정
  frontend/src/components/Notification/Notification.styled.ts
  frontend/src/components/Notification/Notification.tsx
Labels: 🚨 버그, 💻 프론트엔드

#320 [BE] feed thread 조회 시 MemberTeamPlace의 DisplayMemberName으로 조회되도록 변경
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
Labels: 🍃 백엔드, 💡 기능

#323 [FE] 일정 등록 접근성 개선
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Menu/MenuList/MenuList.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: 💻 프론트엔드, 💡 기능

#318 [FE] pageTemplate width 줄이기
  frontend/src/components/pages/PageTemplate/PageTemplate.styled.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#329 [FE] 홈페이지 favicon 적용
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: 💻 프론트엔드, 💡 기능

#327 [FE]팀 전환 기능 구현
  frontend/.storybook/preview.tsx
  frontend/src/components/Calendar/Calendar.stories.tsx
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/DailyScheduleModal/DailyScheduleModal.styled.ts
  frontend/src/components/DailyScheduleModal/DailyScheduleModal.tsx
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.stories.tsx
  frontend/src/components/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/ScheduleBar/ScheduleBar.tsx
  frontend/src/components/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/ThreadList/ThreadList.tsx
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/common/TeamPlaceMenu/TeamPlaceMenu.stories.tsx
  frontend/src/components/common/TeamPlaceMenu/TeamPlaceMenu.styled.ts
  frontend/src/components/common/TeamPlaceMenu/TeamPlaceMenu.tsx
  frontend/src/components/pages/TempLandingPage/TempLandingPage.styled.ts
  frontend/src/components/pages/TempLandingPage/TempLandingPage.tsx
  frontend/src/contexts/TeamPlaceContext.tsx
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/hooks/schedule/useScheduleEditModal.ts
  frontend/src/hooks/thread/useThreadAddBottomSheet.ts
  frontend/src/index.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/team.ts
  frontend/src/utils/getInfoByTeamPlaceId.ts
Labels: 💻 프론트엔드, 💡 기능

#333 [FE] 새로고침 팀 초기화 버그 수정
  frontend/src/components/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/contexts/TeamPlaceContext.tsx
  frontend/src/hooks/schedule/useScheduleAddModal.ts
Labels: 🚨 버그, 💻 프론트엔드

#337 [FE] Thread 스토리북 테스트 수정
  frontend/src/components/Thread/Thread.stories.ts
Labels: 💻 프론트엔드, 🤖 테스트

#332 [BE] 코드 스타일 포멧팅 관리
  backend/src/main/java/team/teamby/teambyteam/auth/exception/AuthenticationException.java
  backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenProvider.java
  backend/src/main/java/team/teamby/teambyteam/feed/exception/FeedException.java
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/ProfileImageUrl.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleEvent.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleUpdateEvent.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/ScheduleRepository.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamCalendarScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/MemberFixtures.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/NotificationServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/domain/NoticeRepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/MyCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/ScheduleRepositoryTest.java
Labels: 🍃 백엔드

#347 [FE] 시간 설정하지 않고 종일 일정 등록 실패 현상 수정
  frontend/src/hooks/schedule/useScheduleAddModal.ts
Labels: 🚨 버그, 💻 프론트엔드

#359 [FE] 바텀시트가 화면 하단에 고정되지 않는 현상 수정
  frontend/src/components/pages/FeedPage/FeedPage.styled.ts
  frontend/src/components/pages/FeedPage/FeedPage.tsx
Labels: 🚨 버그, 💻 프론트엔드

#325 [BE] 팀 공지 조회 시 member team place의 display name이 조회되도록 기능 변경
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeResponse.java
  backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
  backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
Labels: 🍃 백엔드, 💡 기능

#365 [BE] MemberArgumentResolver에서 JwtTokenProvider 사용하도록 리팩토링
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberArgumentResolver.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
Labels: 🍃 백엔드, 🔨 리팩터링

#368 [BE] MemberTeamPlaceRepository 반환데이터 변경
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberIdAndDisplayNameOnly.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeResponse.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepositoryTest.java
Labels: 🍃 백엔드, 🔨 리팩터링

#369 [BE] 최종 redirect url의 param에 토큰을 포함하도록 구현
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java
Labels: 🍃 백엔드, 💡 기능

#371 [FE] 구글 로그인 테스트 버튼 구현
  frontend/src/apis/auth.ts
  frontend/src/pages/LandingPage/LandingPage.styled.ts
  frontend/src/pages/LandingPage/LandingPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#372 [BE] 구글 oauth시 로그인 url을 redirect가 아닌 body로 담아주도록 변경
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/dto/GoogleLoginUrlResponse.java
Labels: 🍃 백엔드, 🔨 리팩터링

#375 [FE] 로그인 버튼 클릭시 구글 로그인 redirect 구현
  frontend/src/apis/auth.ts
  frontend/src/pages/LandingPage/LandingPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#383 [FE]소셜 로그인 accesstToken 로컬에 저장하는 기능
  frontend/src/App.tsx
  frontend/src/constants/routes.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#384 [FE] 로그인 성공시 페이지 이동
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#386 [FE] 로그인 안한 유저일 시 랜딩 페이지로 이동
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/contexts/TeamPlaceContext.tsx
  frontend/src/index.tsx
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/PageTemplate/PageTemplate.tsx
Labels: 💻 프론트엔드, 💡 기능

#388 [FE] 로그인한 유저 정보로 API 요청 보내기
  frontend/src/apis/http.ts
Labels: 💻 프론트엔드, 💡 기능

#387 [BE] 팀플래이스 생성 api. 구현
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceCreateRequest.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceCreateResponse.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamPlaceAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java
Labels: 🍃 백엔드, 💡 기능

#404 [BE] 팀플레이스 초대코드 조회 구현
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceInviteCodeResponse.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/RandomInviteCodeGenerator.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceInviteCode.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceInviteCodeRepository.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/vo/InviteCode.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceInviteCodeException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/BuilderSupporter.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/TeamPlaceInviteCodeFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamPlaceAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceInviteCodeRepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/vo/InviteCodeTest.java
  backend/src/test/resources/h2-truncate.sql
Labels: 🍃 백엔드, 💡 기능

#403 [FE] 종일 일정 등록 버그 수정
  frontend/src/components/common/SideBar/SideBar.styled.ts
  frontend/src/components/feed/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/pages/TeamCalendarPage/TeamCalendarPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
Labels: 🚨 버그, 💻 프론트엔드, 🔨 리팩터링

#408 [ALL] dev서버 배포 워크플로우 수정
  .github/workflows/backend-dev-branch-build-and-upload.yml
  .github/workflows/frontend-cd.yml
Labels: 🍃 백엔드, 💻 프론트엔드, ⚙️ 환경설정

#409 [ALL] 배포 워크플로우 오류 수정
  .github/workflows/backend-dev-branch-build-and-upload.yml
  .github/workflows/frontend-cd.yml
Labels: 🍃 백엔드, 💻 프론트엔드, ⚙️ 환경설정

#410 [BE] 누락된 백엔드 배포 플로우 추가
  .github/workflows/backend-dev-branch-build-and-upload.yml
Labels: 🍃 백엔드, ⚙️ 환경설정

#411 [FE] 프런트 배포 워크플로우 수정
  .github/workflows/frontend-cd.yml
Labels: 💻 프론트엔드, ⚙️ 환경설정

#412 [ALL] 깃헙 워크플로우 네임 변경, 개발서버 배포 버튼 제거
  .github/workflows/backend-ci.yml
  .github/workflows/backend-deploy-dev.yml
  .github/workflows/frontend-ci.yml
  .github/workflows/frontend-deploy-dev.yml
Labels: 🍃 백엔드, 💻 프론트엔드, ⚙️ 환경설정

#405 [FE] 로그아웃 기능 구현
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/logout.svg
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
Labels: 💻 프론트엔드, 💡 기능

#417 [FE]팀 참가, 생성 페이지 구현
  frontend/src/App.tsx
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/components/common/Text/Text.styled.ts
  frontend/src/components/common/Text/Text.tsx
  frontend/src/constants/routes.tsx
  frontend/src/contexts/TeamPlaceContext.tsx
  frontend/src/hooks/queries/useFetchTeamPlaces.ts
  frontend/src/pages/CreatePage/CreatePage.styled.ts
  frontend/src/pages/CreatePage/CreatePage.tsx
  frontend/src/pages/JoinPage/JoinPage.styled.tsx
  frontend/src/pages/JoinPage/JoinPage.tsx
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/PageTemplate/PageTemplate.tsx
  frontend/src/pages/StartPage/StartPage.styled.ts
  frontend/src/pages/StartPage/StartPage.tsx
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#421 [FE] 서버에서 로그인이 안되는 현상
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: 🚨 버그, 💻 프론트엔드

#406 [BE] 팀플레이스 가입 구현
  backend/src/main/java/team/teamby/teambyteam/auth/presentation/TeamPlaceParticipationInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
  backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceParticipantResponse.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceInviteCodeRepository.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/vo/InviteCode.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceInviteCodeRepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/vo/InviteCodeTest.java
Labels: 🍃 백엔드, 💡 기능

#419 [BE] 문서화 공통 클래스 ApiDocsTest 구현
  backend/src/test/java/team/teamby/teambyteam/common/ApiDocsTest.java
Labels: 🍃 백엔드, 📑 문서, 🤖 테스트

#407 [BE] Refresh Token 로직 구현
  backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenExtractor.java
  backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenProvider.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
  backend/src/main/java/team/teamby/teambyteam/auth/presentation/MemberInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/auth/presentation/TeamPlaceParticipationInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebMvcConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/member/configuration/MemberArgumentResolver.java
  backend/src/main/java/team/teamby/teambyteam/token/application/TokenService.java
  backend/src/main/java/team/teamby/teambyteam/token/application/dto/TokenResponse.java
  backend/src/main/java/team/teamby/teambyteam/token/domain/Token.java
  backend/src/main/java/team/teamby/teambyteam/token/domain/TokenRepository.java
  backend/src/main/java/team/teamby/teambyteam/token/exception/TokenException.java
  backend/src/main/java/team/teamby/teambyteam/token/presentation/TokenController.java
  backend/src/main/resources/application.yml
  backend/src/test/java/team/teamby/teambyteam/auth/jwt/JwtTokenProviderTest.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/BuilderSupporter.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/TokenFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TokenAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/MyCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/token/acceptance/TokenAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/token/application/TokenServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/token/domain/TokenRepositoryTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/h2-truncate.sql
Labels: 🍃 백엔드, 💡 기능

#430 [BE] 팀플레이스 생성 요청시 예외 코드 오류 수정
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceCreateRequest.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
Labels: 🚨 버그, 🍃 백엔드

#431 [FE] 팀 참가, 생성 api 구현 및 연결
  frontend/src/apis/http.ts
  frontend/src/apis/team.ts
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/team-add.svg
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/constants/localStorage.ts
  frontend/src/constants/team.ts
  frontend/src/contexts/TeamPlaceContext.tsx
  frontend/src/hooks/queries/useSendCreateTeamPlace.ts
  frontend/src/hooks/queries/useSendJoinTeamPlace.ts
  frontend/src/hooks/team/useTeamCreate.ts
  frontend/src/hooks/team/useTeamJoin.ts
  frontend/src/mocks/fixtures/team.ts
  frontend/src/mocks/handlers/team.ts
  frontend/src/pages/CreatePage/CreatePage.tsx
  frontend/src/pages/JoinPage/JoinPage.styled.tsx
  frontend/src/pages/JoinPage/JoinPage.tsx
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/StartPage/StartPage.tsx
  frontend/src/pages/TeamSelectPage/TeamSelectPage.tsx
  frontend/src/types/team.ts
Labels: 💻 프론트엔드, 💡 기능

#433 [FE] 팀플레이스 탈퇴 기능 구현
  frontend/src/apis/http.ts
  frontend/src/apis/team.ts
  frontend/src/assets/svg/exit.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/team/TeamBadge/TeamBadge.stories.ts
  frontend/src/components/team/TeamExitModal/TeamExitModal.stories.tsx
  frontend/src/components/team/TeamExitModal/TeamExitModal.styled.ts
  frontend/src/components/team/TeamExitModal/TeamExitModal.tsx
  frontend/src/contexts/TeamPlaceContext.tsx
  frontend/src/hooks/queries/useDeleteTeamPlace.ts
  frontend/src/hooks/team/useTeamExitModal.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/team.ts
  frontend/src/pages/PageTemplate/PageTemplate.tsx
Labels: 💻 프론트엔드, 💡 기능

#437 [FE] 참여코드를 초대코드로 바꾸기
  frontend/src/hooks/team/useTeamJoin.ts
  frontend/src/pages/JoinPage/JoinPage.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#435 [FE] 로그인 버튼 및 랜딩 페이지 구현
  frontend/src/assets/png/google-logo.png
  frontend/src/assets/png/index.ts
  frontend/src/assets/png/mouse-pointer.png
  frontend/src/assets/svg/folder-open.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/landing/FeedDecoration/FeedDecoration.stories.tsx
  frontend/src/components/landing/FeedDecoration/FeedDecoration.styled.ts
  frontend/src/components/landing/FeedDecoration/FeedDecoration.tsx
  frontend/src/components/landing/FileDriveDecoration/FileDriveDecoration.stories.tsx
  frontend/src/components/landing/FileDriveDecoration/FileDriveDecoration.styled.ts
  frontend/src/components/landing/FileDriveDecoration/FileDriveDecoration.tsx
  frontend/src/components/landing/IntroCardPile/IntroCardPile.stories.tsx
  frontend/src/components/landing/IntroCardPile/IntroCardPile.styled.ts
  frontend/src/components/landing/IntroCardPile/IntroCardPile.tsx
  frontend/src/components/landing/TeamCalendarDecoration/TeamCalendarDecoration.stories.tsx
  frontend/src/components/landing/TeamCalendarDecoration/TeamCalendarDecoration.styled.ts
  frontend/src/components/landing/TeamCalendarDecoration/TeamCalendarDecoration.tsx
  frontend/src/constants/landing.ts
  frontend/src/pages/LandingPage/LandingPage.styled.ts
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#445 [FE] 랜딩 페이지의 장식 컴포넌트를 3개의 메뉴에도 적용
  frontend/src/pages/CreatePage/CreatePage.tsx
  frontend/src/pages/JoinPage/JoinPage.tsx
  frontend/src/pages/StartPage/StartPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#453 [BE] 공지 작성자 표기 오류 수정
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
Labels: 🚨 버그, 🍃 백엔드

#454 [BE] 멤버 이름 최대 길이 넘으면 잘라서 저장하도록 버그 수정
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java
Labels: 🚨 버그, 🍃 백엔드

#456 [BE] 예외상황 로깅 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
  backend/src/test/resources/application.yml
Labels: 🍃 백엔드, 💡 기능, ⚙️ 환경설정

#460 [BE] 내정보 조회 API 구현
  backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
  backend/src/main/java/team/teamby/teambyteam/member/application/dto/MemberInfoResponse.java
  backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
Labels: 🍃 백엔드, 💡 기능

#459 [FE] 팀 링크 추가 UI 와 API 구현
  frontend/src/apis/link.ts
  frontend/src/components/link/LinkAddModal/LinkAddModal.stories.tsx
  frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
  frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
  frontend/src/hooks/link/useTeamLinkAddModal.ts
  frontend/src/hooks/queries/useSendTeamLink.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/link.ts
  frontend/src/types/link.ts
Labels: 💻 프론트엔드, 💡 기능

#465 [BE] 구글 로그인 시 리프레시 토큰도 발급하도록 리팩토링
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/dto/TokenResponse.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java
Labels: 🍃 백엔드, 🔨 리팩터링

#471 [BE] 구글 OAuth 요청 2회 나가는 오류 수정
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/presentation/AuthController.java
Labels: 🚨 버그, 🍃 백엔드

#466 [FE] 토큰 만료시 refershToken으로 재발급 요청
  frontend/src/apis/auth.ts
  frontend/src/apis/http.ts
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/constants/localStorage.ts
  frontend/src/hooks/queries/useSendTokenReissue.ts
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#469 [BE] 팀 플레이스 참여 멤버 조회
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
  backend/src/main/java/team/teamby/teambyteam/member/application/dto/TeamPlaceResponse.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepository.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeResponse.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMemberResponse.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMembersResponse.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamPlaceAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/MemberTeamPlaceRepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java
Labels: 🍃 백엔드, 💡 기능

#477 [FE] 라우터가 요구되는 컴포넌트를 스토리북에서 확인할 수 있도록 스토리북에 라우터를 추가
  frontend/.storybook/preview.tsx
Labels: 💻 프론트엔드, ⚙️ 환경설정

#470 [BE] INFO 레벨 로깅 추가 및 로깅용 메시지 변경
  backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenProvider.java
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
  backend/src/main/java/team/teamby/teambyteam/auth/presentation/MemberInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/auth/presentation/TeamPlaceParticipationInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/NotificationService.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/ScheduleNotification.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/vo/Content.java
  backend/src/main/java/team/teamby/teambyteam/feed/exception/FeedException.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/ErrorResponse.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberName.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/DisplayTeamPlaceName.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Email.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java
  backend/src/main/java/team/teamby/teambyteam/member/exception/MemberException.java
  backend/src/main/java/team/teamby/teambyteam/member/exception/MemberTeamPlaceException.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/vo/Content.java
  backend/src/main/java/team/teamby/teambyteam/notice/exception/NoticeException.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/vo/Span.java
  backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/vo/InviteCode.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/vo/Name.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceInviteCodeException.java
  backend/src/main/java/team/teamby/teambyteam/token/application/TokenService.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/domain/vo/ContentTest.java
  backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberNameTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayTeamPlaceNameTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/EmailTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/NameTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/domain/vo/ContentTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/acceptance/TeamCalendarScheduleAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/domain/SpanTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/domain/NameTest.java
  backend/src/test/java/team/teamby/teambyteam/token/acceptance/TokenAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/token/application/TokenServiceTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 💡 기능

#475 [FE] 팀 링크 페이지 구현
  frontend/src/App.tsx
  frontend/src/apis/link.ts
  frontend/src/assets/png/index.ts
  frontend/src/assets/png/link-empty-image.png
  frontend/src/assets/svg/chain.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/link/EmptyLinkPlaceholder/EmptyLinkPlaceholder.stories.tsx
  frontend/src/components/link/EmptyLinkPlaceholder/EmptyLinkPlaceholder.styled.ts
  frontend/src/components/link/EmptyLinkPlaceholder/EmptyLinkPlaceholder.tsx
  frontend/src/components/link/LinkTable/LinkTable.stories.tsx
  frontend/src/components/link/LinkTable/LinkTable.styled.ts
  frontend/src/components/link/LinkTable/LinkTable.tsx
  frontend/src/constants/link.ts
  frontend/src/constants/routes.tsx
  frontend/src/hooks/queries/useDeleteTeamLink.ts
  frontend/src/hooks/queries/useFetchTeamLinks.tsx
  frontend/src/hooks/queries/useSendTeamLink.ts
  frontend/src/mocks/fixtures/link.ts
  frontend/src/mocks/handlers/link.ts
  frontend/src/pages/TeamLinkPage/TeamLinkPage.styled.ts
  frontend/src/pages/TeamLinkPage/TeamLinkPage.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/types/link.ts
Labels: 💻 프론트엔드, 💡 기능

#481 [FE] 토크 재발급 에러 발생시 렌딩으로 이동
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/hooks/queries/useSendTokenReissue.ts
Labels: 🚨 버그, 💻 프론트엔드

#478 [BE] 리프레시 토큰 발급 시 DB 저장하도록 버그 fix
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
Labels: 🚨 버그, 🍃 백엔드, 🔨 리팩터링

#473 [BE] 팀공유링크 추가 조회 삭제 기능 구현
  backend/src/main/java/team/teamby/teambyteam/feed/application/NotificationService.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/schedulenotification/ScheduleNotification.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/schedulenotification/ScheduleNotificationContentGenerator.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/schedulenotification/ScheduleNotificationFactory.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/sharedlinknotification/SharedLinkNotification.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/sharedlinknotification/SharedLinkNotificationContentGenerator.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/sharedlinknotification/SharedLinkNotificationFactory.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/dto/SharedLinkCreateRequest.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/dto/SharedLinkResponse.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/dto/SharedLinksResponse.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/EventType.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/SharedLinkCreateEvent.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/SharedLinkDeleteEvent.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/SharedLinkEvent.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLinkRepository.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/vo/SharedURL.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/vo/Title.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/exception/SharedLinkException.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/presentation/SharedLinkController.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/BuilderSupporter.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/SharedLinkEventFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/SharedLinkFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/SharedLinkAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/NotificationServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/domain/FeedRepositoryTest.java
  backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/sharedlink/application/SharedLinkServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/sharedlink/domain/vo/SharedURLTest.java
  backend/src/test/java/team/teamby/teambyteam/sharedlink/domain/vo/TitleTest.java
  backend/src/test/resources/h2-truncate.sql
Labels: 🍃 백엔드, 💡 기능

#483 [FE] API 응답 타입 리팩터링
  frontend/src/apis/auth.ts
  frontend/src/apis/feed.ts
  frontend/src/apis/http.ts
  frontend/src/apis/link.ts
  frontend/src/apis/schedule.ts
  frontend/src/apis/team.ts
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/types/team.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#494 [BE] 리프레시 토큰이 db에 있는 사용자의 재 로그인시 오류 수정
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
  backend/src/main/java/team/teamby/teambyteam/token/application/TokenService.java
  backend/src/main/java/team/teamby/teambyteam/token/domain/TokenRepository.java
  backend/src/main/java/team/teamby/teambyteam/token/exception/TokenException.java
  backend/src/test/java/team/teamby/teambyteam/token/acceptance/TokenAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/token/application/TokenServiceTest.java
Labels: 🚨 버그, 🍃 백엔드

#498 [BE] 운영서버 배포 워크플로우 추가
  .github/workflows/deploy-prod.yml
Labels: 🍃 백엔드, ⚙️ 환경설정

#486 [BE] create, delete 시 info 로깅 추가, 예외 메시지 변경, 예외 로깅시 요청 정보 추가
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/exception/SharedLinkException.java
  backend/src/test/java/team/teamby/teambyteam/sharedlink/acceptance/SharedLinkAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/sharedlink/application/SharedLinkServiceTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 💡 기능, 🤖 테스트

#490 [FE] 모아보기 페이지 구현
  frontend/src/App.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/components/link/LinkTable/LinkTable.tsx
  frontend/src/constants/routes.tsx
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
  frontend/src/pages/TeamOverviewPage/TeamOverviewPage.styled.ts
  frontend/src/pages/TeamOverviewPage/TeamOverviewPage.tsx
  frontend/src/pages/TeamSelectPage/TeamSelectPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#424 [BE] feed api 문서화
  backend/src/docs/asciidoc/feed.adoc
  backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
Labels: 🍃 백엔드, 📑 문서, 🤖 테스트

#500 [BE] member 도메인 api 문서화
  backend/src/docs/asciidoc/member.adoc
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/docs/MemberApiDocsTest.java
Labels: 🍃 백엔드, 📑 문서, 🤖 테스트

#432 [BE] 팀플레이스 관련 API 문서화
  backend/src/docs/asciidoc/teamPlace.adoc
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/TeamPlaceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/docs/TeamPlaceControlApiDocsTest.java
Labels: 🍃 백엔드, 📑 문서, 🤖 테스트

#506 [ALL] 운영서버 배포 워크플로우
  .github/workflows/deploy-prod.yml
Labels: 🍃 백엔드, 💻 프론트엔드, ⚙️ 환경설정

#502 [BE] 공유 링크 api 문서화
  backend/src/docs/asciidoc/sharedlink.adoc
  backend/src/test/java/team/teamby/teambyteam/sharedlink/docs/SharedLinkApiDocsTest.java
Labels: 🍃 백엔드, 📑 문서, 🤖 테스트

#512 [FE] 시맨틱 태그 적용 및 접근성 개선
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/common/SideBar/SideBar.styled.ts
  frontend/src/components/common/SideBar/SideBar.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.tsx
  frontend/src/components/feed/Thread/Thread.tsx
  frontend/src/components/link/EmptyLinkPlaceholder/EmptyLinkPlaceholder.tsx
  frontend/src/components/link/LinkTable/LinkTable.tsx
  frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
  frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#505 [FE] 모아보기 페이지의 팀 링크, 팀 캘린더 뷰 수정
  frontend/src/components/link/EmptyLinkPlaceholder/EmptyLinkPlaceholder.styled.ts
  frontend/src/components/link/LinkTable/LinkTable.styled.ts
  frontend/src/components/link/LinkTable/LinkTable.tsx
  frontend/src/components/my_calendar/MyDailyScheduleList/MyDailyScheduleList.styled.ts
  frontend/src/components/team_calendar/ScheduleBar/ScheduleBar.styled.ts
  frontend/src/components/team_calendar/ScheduleBar/ScheduleBar.tsx
  frontend/src/components/team_calendar/ScheduleMoreCell/ScheduleMoreCell.styled.ts
  frontend/src/components/team_calendar/ScheduleMoreCell/ScheduleMoreCell.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.styled.ts
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/constants/link.ts
  frontend/src/mocks/fixtures/schedules.ts
  frontend/src/pages/TeamOverviewPage/TeamOverviewPage.styled.ts
  frontend/src/pages/TeamOverviewPage/TeamOverviewPage.tsx
  frontend/src/types/size.ts
Labels: 💻 프론트엔드, 💡 기능

#508 [BE] 운영서버 로깅 설정 작성
  backend/src/main/resources/logback-spring.xml
Labels: 🍃 백엔드, ⚙️ 환경설정

#479 [BE] 토큰 재발급 문서화
  backend/src/docs/asciidoc/token.adoc
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/TokenFixtures.java
  backend/src/test/java/team/teamby/teambyteam/token/docs/TokenApiDocsTest.java
Labels: 🍃 백엔드, 📑 문서, 🤖 테스트

#516 [ALL] 배포 관련 워크플로우 추가 변경
  .github/workflows/backend-deploy-dev-docs.yml
  .github/workflows/deploy-prod-by-realease-tag.yml
  .github/workflows/deploy-prod-latest.yml
  .github/workflows/frontend-deploy-dev.yml
Labels: 🍃 백엔드, 💻 프론트엔드, ⚙️ 환경설정

#518 [BE] index.adoc에 도메인 adoc Include 리팩토링
  backend/src/docs/asciidoc/index.adoc
Labels: 🍃 백엔드, 🔨 리팩터링, 📑 문서

#519 [FE] 스레드 무한 스크롤 fetchNextPage에 teamPlaceId 판별 조건문 추가
  frontend/src/components/feed/ThreadList/ThreadList.tsx
Labels: 🚨 버그, 💻 프론트엔드

#492 [FE] 알림 목록 모달 컴포넌트 구현
  frontend/src/assets/svg/bell.svg
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/team.svg
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/feed/NotificationListModal/NotificationListModal.stories.tsx
  frontend/src/components/feed/NotificationListModal/NotificationListModal.styled.ts
  frontend/src/components/feed/NotificationListModal/NotificationListModal.tsx
  frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
  frontend/src/hooks/queries/useFetchNotifications.ts
Labels: 💻 프론트엔드, 💡 기능

#522 [BE] Docs 404 예외 스타일 추가
  backend/src/docs/asciidoc/index.adoc
Labels: 🍃 백엔드, 🔨 리팩터링, 📑 문서

#529 [FE] 피드의 마지막에서 스레드가 등록되지 않는 현상
  frontend/src/components/feed/NotificationListModal/NotificationListModal.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/hooks/useIntersectionObserver.ts
Labels: 🚨 버그, 💻 프론트엔드

#536 [FE] favicon 적용되도록 HtmlWebpackPlugin 옵션 수정
  frontend/webpack.config.js
Labels: 💻 프론트엔드, ⚙️ 환경설정

#524 [FE] 모아보기 페이지 피드 UI 개선
  frontend/src/components/feed/NoticeThread/NoticeThread.stories.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.tsx
  frontend/src/components/feed/Notification/Notification.stories.ts
  frontend/src/components/feed/Notification/Notification.styled.ts
  frontend/src/components/feed/Notification/Notification.tsx
  frontend/src/components/feed/Thread/Thread.stories.ts
  frontend/src/components/feed/Thread/Thread.styled.ts
  frontend/src/components/feed/Thread/Thread.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#538 [FE] 랜딩 페이지 애니메이션 등장 타이밍 수정
  frontend/src/components/landing/IntroCardPile/IntroCardPile.styled.ts
  frontend/src/components/landing/TeamCalendarDecoration/TeamCalendarDecoration.styled.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#530 [FE] 레이아웃 깨지는 현상 수정
  frontend/src/assets/svg/arrow-expand-less.svg
  frontend/src/assets/svg/arrow-expand-more.svg
  frontend/src/assets/svg/arrow-left2.svg
  frontend/src/assets/svg/arrow-up.svg
  frontend/src/assets/svg/bell.svg
  frontend/src/assets/svg/calendar.svg
  frontend/src/assets/svg/chain.svg
  frontend/src/assets/svg/check.svg
  frontend/src/assets/svg/close.svg
  frontend/src/assets/svg/delete.svg
  frontend/src/assets/svg/double-arrow-right.svg
  frontend/src/assets/svg/drive.svg
  frontend/src/assets/svg/edit.svg
  frontend/src/assets/svg/exit.svg
  frontend/src/assets/svg/feed.svg
  frontend/src/assets/svg/folder-open.svg
  frontend/src/assets/svg/home.svg
  frontend/src/assets/svg/megaphone.svg
  frontend/src/assets/svg/plus.svg
  frontend/src/assets/svg/team-add.svg
  frontend/src/assets/svg/team.svg
  frontend/src/assets/svg/write.svg
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/feed/NotificationListModal/NotificationListModal.tsx
  frontend/src/components/feed/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
  frontend/src/components/feed/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
  frontend/src/components/my_calendar/MyDailyScheduleList/MyDailyScheduleList.styled.ts
  frontend/src/pages/JoinPage/JoinPage.styled.tsx
  frontend/src/pages/PageTemplate/PageTemplate.styled.ts
  frontend/src/pages/PageTemplate/PageTemplate.tsx
  frontend/src/pages/TeamCalendarPage/TeamCalendarPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 🚨 버그, 💻 프론트엔드, 🔨 리팩터링

#543 [ALL] Pre-Release v0.2.0
  frontend/src/assets/svg/arrow-expand-less.svg
  frontend/src/assets/svg/arrow-expand-more.svg
  frontend/src/assets/svg/arrow-left2.svg
  frontend/src/assets/svg/arrow-up.svg
  frontend/src/assets/svg/bell.svg
  frontend/src/assets/svg/calendar.svg
  frontend/src/assets/svg/chain.svg
  frontend/src/assets/svg/check.svg
  frontend/src/assets/svg/close.svg
  frontend/src/assets/svg/delete.svg
  frontend/src/assets/svg/double-arrow-right.svg
  frontend/src/assets/svg/drive.svg
  frontend/src/assets/svg/edit.svg
  frontend/src/assets/svg/exit.svg
  frontend/src/assets/svg/feed.svg
  frontend/src/assets/svg/folder-open.svg
  frontend/src/assets/svg/home.svg
  frontend/src/assets/svg/megaphone.svg
  frontend/src/assets/svg/plus.svg
  frontend/src/assets/svg/team-add.svg
  frontend/src/assets/svg/team.svg
  frontend/src/assets/svg/write.svg
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.stories.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.tsx
  frontend/src/components/feed/Notification/Notification.stories.ts
  frontend/src/components/feed/Notification/Notification.styled.ts
  frontend/src/components/feed/Notification/Notification.tsx
  frontend/src/components/feed/NotificationListModal/NotificationListModal.tsx
  frontend/src/components/feed/Thread/Thread.stories.ts
  frontend/src/components/feed/Thread/Thread.styled.ts
  frontend/src/components/feed/Thread/Thread.tsx
  frontend/src/components/feed/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
  frontend/src/components/feed/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/components/landing/IntroCardPile/IntroCardPile.styled.ts
  frontend/src/components/landing/TeamCalendarDecoration/TeamCalendarDecoration.styled.ts
  frontend/src/components/my_calendar/MyDailyScheduleList/MyDailyScheduleList.styled.ts
  frontend/src/hooks/useIntersectionObserver.ts
  frontend/src/pages/JoinPage/JoinPage.styled.tsx
  frontend/src/pages/PageTemplate/PageTemplate.styled.ts
  frontend/src/pages/PageTemplate/PageTemplate.tsx
  frontend/src/pages/TeamCalendarPage/TeamCalendarPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
  frontend/webpack.config.js
Labels: 🍃 백엔드, 💻 프론트엔드, 🚛배포

#534 [FE] 팀 링크에서 https:// 로 시작하지 않는 경우 잘못된 주소로 이동하는 문제 해결
  frontend/src/components/link/LinkTable/LinkTable.tsx
  frontend/src/hooks/link/useTeamLinkAddModal.ts
  frontend/src/utils/generateHttpsUrl.ts
Labels: 🚨 버그, 💻 프론트엔드

#539 [FE] 모아보기 페이지 모달 UI 개선
  frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
  frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
  frontend/src/components/link/LinkTable/LinkTable.tsx
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.styled.ts
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.tsx
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#484 [BE] 공지 등록 및 조회 기능 문서화
  backend/src/docs/asciidoc/notice.adoc
  backend/src/test/java/team/teamby/teambyteam/notice/docs/NoticeApiDocsTest.java
Labels: 🍃 백엔드, 📑 문서

#546 [FE] 알림 목록 줄바꿈 수정
  frontend/src/components/feed/NotificationListModal/NotificationListModal.styled.ts
  frontend/src/hooks/team/useTeamCreate.ts
  frontend/src/mocks/fixtures/threads.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#540 [FE] 팀 캘린더 메뉴 모달위치 교정
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.stories.tsx
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.styled.ts
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.stories.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/hooks/useCalendarResizePosition.ts
Labels: 🚨 버그, 💻 프론트엔드

#544 [FE] 헤더 로고 위치 고정
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/LandingHeader/LandingHeader.styled.ts
Labels: 💻 프론트엔드, 💡 기능

#553 [ALL] main 브렌치 발생 release만 배포
  .github/workflows/deploy-prod-latest.yml
Labels: ⚙️ 환경설정, 🚛배포

#554 [ALL] v1.0.0 README 작성
  README.md
Labels: 🍃 백엔드, 💻 프론트엔드, 📑 문서

#552 [FE] 팀 이름이 길면 선택칸 보다 넘치는 버그 수정
  frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.styled.ts
  frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.tsx
Labels: 🚨 버그, 💻 프론트엔드

#551 [FE] 가입된 팀이 없는 경우 로고 클릭 시 메인 페이지 이동 방지
  frontend/src/App.tsx
  frontend/src/components/common/LandingHeader/LandingHeader.styled.ts
  frontend/src/components/common/LandingHeader/LandingHeader.tsx
Labels: 🚨 버그, 💻 프론트엔드

#555 Release v1.0.0
  .github/workflows/deploy-prod-latest.yml
  README.md
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/myScehdule.adoc
  backend/src/docs/asciidoc/notice.adoc
  backend/src/main/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/MyCalendarScheduleController.java
  backend/src/main/java/team/teamby/teambyteam/schedule/presentation/TeamCalendarScheduleController.java
  backend/src/test/java/team/teamby/teambyteam/notice/docs/NoticeApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/MyCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/MyCalendarScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
  frontend/src/App.tsx
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/LandingHeader/LandingHeader.styled.ts
  frontend/src/components/common/LandingHeader/LandingHeader.tsx
  frontend/src/components/feed/NotificationListModal/NotificationListModal.styled.ts
  frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
  frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
  frontend/src/components/link/LinkTable/LinkTable.tsx
  frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.styled.ts
  frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.tsx
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.stories.tsx
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.styled.ts
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.tsx
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.stories.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/hooks/link/useTeamLinkAddModal.ts
  frontend/src/hooks/queries/useDeleteSchedule.ts
  frontend/src/hooks/queries/useDeleteTeamLink.ts
  frontend/src/hooks/queries/useModifySchedule.ts
  frontend/src/hooks/queries/useSendSchedule.ts
  frontend/src/hooks/queries/useSendTeamLink.ts
  frontend/src/hooks/team/useTeamCreate.ts
  frontend/src/hooks/useCalendarResizePosition.ts
  frontend/src/mocks/fixtures/threads.ts
  frontend/src/utils/generateHttpsUrl.ts
Labels: 🚛배포

#560 [FE] 시작 페이지에 뒤로가기 버튼 추가
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/pages/StartPage/StartPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#559 [FE] 팀 참가에서 엔터누를 시 생성 페이지로 이동하는 버그
  frontend/src/pages/JoinPage/JoinPage.tsx
Labels: 🚨 버그, 💻 프론트엔드

#562 Release v1.0.1
  frontend/src/assets/png/feed-empty-image.png
  frontend/src/assets/png/index.ts
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/common/NavigationBar/NavigationBar.tsx
  frontend/src/components/feed/EmptyFeedPlaceholder/EmptyFeedPlaceholder.stories.tsx
  frontend/src/components/feed/EmptyFeedPlaceholder/EmptyFeedPlaceholder.styled.ts
  frontend/src/components/feed/EmptyFeedPlaceholder/EmptyFeedPlaceholder.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/pages/JoinPage/JoinPage.tsx
  frontend/src/pages/StartPage/StartPage.tsx
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 🚛배포

#565 [BE] 500 에러 로깅용 코드 작성(에러 메시지 반환은 하지 않음)
  backend/src/main/java/team/teamby/teambyteam/auth/exception/AuthenticationException.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
Labels: 🍃 백엔드, 💡 기능, ⚙️ 환경설정

#568 [BE] final 추가
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
Labels: 🍃 백엔드, 🔨 리팩터링

#566 [BE] 디렉토리 삭제 안되는 문제 해결
  .github/workflows/backend-deploy-dev.yml
Labels: 🚨 버그, 🍃 백엔드, ⚙️ 환경설정

#571 [BE] 예외상황시 발생로그 레벨 변경
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
Labels: 🍃 백엔드, 🔨 리팩터링

#572 [BE] url base64 디코딩 문제 해결
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
Labels: 🚨 버그, 🍃 백엔드

#573 [BE] 캐스팅시 문제 해결
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
Labels: 🚨 버그, 🍃 백엔드

#574 Release v1.0.3
  backend/src/main/java/team/teamby/teambyteam/auth/oauth/application/GoogleOAuthService.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
Labels: 🚛배포
