Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2023-09, with the labels that each got.

#582 [FE] 토큰 재발급시 중복 요청 보내는 트러블 슈팅
  frontend/src/apis/auth.ts
Labels: 🚨 버그, 💻 프론트엔드

#598 [FE] 토큰 재발급 동안 중복 요청 보내는 버그
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
Labels: 🚨 버그, 💻 프론트엔드

#602 [토큰 재발급이 한번만 실행되는 현상
  frontend/src/apis/auth.ts
  frontend/src/hooks/queries/useSendTokenReissue.ts
Labels: 🚨 버그, 💻 프론트엔드

#606 [FE] 일정 등록 시간 기본값을 09:00 ~ 10:00으로 수정
  frontend/src/hooks/schedule/useScheduleAddModal.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#599 [BE] 소속된 팀의 팀원 조회시 본인 여부 필드 추가
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMemberResponse.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMembersResponse.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 💡 기능

#590 [BE] 팀플레이스 색상 변경 기능 / 문서화 구현
  backend/src/docs/asciidoc/teamPlace.adoc
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/TeamPlaceColor.java
  backend/src/main/java/team/teamby/teambyteam/member/exception/MemberTeamPlaceException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceChangeColorRequest.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamPlaceAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/TeamPlaceColorTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/docs/TeamPlaceControlApiDocsTest.java
Labels: 🍃 백엔드, 💡 기능, 📑 문서

#605 [ALL] PR이 올라올 때마다 변경사항에 따른 적합한 리뷰어를 자동 배정하도록 설정
  .github/CODEOWNERS
Labels: ⚙️ 환경설정

#610 [BE] 팀플래이스에서 보일 내 별명 변경 기능 구현
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberName.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/TeamPlaceService.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/DisplayMemberNameChangeRequest.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/application/dto/TeamPlaceMemberResponse.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/presentation/TeamPlaceController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/TeamPlaceAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/DisplayMemberNameTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/application/TeamPlaceServiceTest.java
Labels: 🚨 버그, 🍃 백엔드, 💡 기능

#601 [BE] 회원 탈퇴 api 구현
  backend/src/docs/asciidoc/member.adoc
  backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
  backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/docs/MemberApiDocsTest.java
Labels: 🍃 백엔드, 💡 기능

#612 [ALL] 잘못된 CODEOWNERS 파일 수정
  .github/CODEOWNERS
Labels: 🚨 버그, ⚙️ 환경설정

#614 [BE] MemberInterceptor 예외 401로 변경 + 인증 예외 로깅 리팩토링
  backend/src/main/java/team/teamby/teambyteam/auth/exception/AuthenticationException.java
  backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenExtractor.java
  backend/src/main/java/team/teamby/teambyteam/auth/jwt/JwtTokenProvider.java
  backend/src/main/java/team/teamby/teambyteam/auth/presentation/MemberInterceptor.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/test/java/team/teamby/teambyteam/auth/jwt/JwtTokenProviderTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/docs/MemberApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/sharedlink/docs/SharedLinkApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/teamplace/acceptance/TeamPlaceAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/token/application/TokenServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/token/docs/TokenApiDocsTest.java
Labels: 🍃 백엔드, 🔨 리팩터링

#575 [FE] 개인정보정책 페이지 추가
  frontend/src/App.tsx
  frontend/src/constants/routes.ts
  frontend/src/pages/PolicyPage/PolicyPage.styled.ts
  frontend/src/pages/PolicyPage/PolicyPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#613 [BE] 토큰 DDL NOT NULL, UNIQUE 설정 추가
  backend/src/main/java/team/teamby/teambyteam/token/domain/Token.java
Labels: 🍃 백엔드, 🔨 리팩터링

#609 [BE] 회원정보 수정 기능 구현
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
  backend/src/main/java/team/teamby/teambyteam/member/configuration/dto/MemberUpdateRequest.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/vo/Name.java
  backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/domain/vo/NameTest.java
Labels: 🍃 백엔드, 💡 기능

#607 [FE] 이전 달과 다음 달의 데이터를 미리 불러오는 기능 구현
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/hooks/queries/usePrefetchSchedules.ts
Labels: 💻 프론트엔드, 💡 기능

#603 [FE] 회원 정보 수정 기능 구현
  frontend/src/apis/auth.ts
  frontend/src/apis/user.ts
  frontend/src/assets/svg/check-black.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/user/UserInfoModal/UserInfoModal.styled.ts
  frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
  frontend/src/constants/user.ts
  frontend/src/hooks/queries/useFetchUserInfo.ts
  frontend/src/hooks/queries/useModifyUserInfo.ts
  frontend/src/hooks/user/useUserInfoModal.ts
  frontend/src/mocks/handlers/auth.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/user.ts
Labels: 💻 프론트엔드, 💡 기능

#641 [FE] 폰트 최적화 및 preload 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/fonts/Pretendard-Black.subset.woff2
  frontend/src/assets/fonts/Pretendard-ExtraBold.subset.woff2
  frontend/src/assets/fonts/Pretendard-Medium.subset.woff2
  frontend/src/assets/fonts/Pretendard-Regular.subset.woff2
  frontend/src/assets/fonts/Pretendard-SemiBold.subset.woff2
  frontend/src/pages/LandingPage/LandingPage.styled.ts
  frontend/webpack.config.js
Labels: 💻 프론트엔드, 🔨 리팩터링

#615 [FE] Menu 컴포넌트 키보드 탐색 기능 구현
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Menu/Menu.stories.tsx
  frontend/src/components/common/Menu/Menu.tsx
  frontend/src/components/common/Menu/MenuButton/MenuButton.tsx
  frontend/src/components/common/Menu/MenuItem/MenuItem.styled.ts
  frontend/src/components/common/Menu/MenuItem/MenuItem.tsx
  frontend/src/components/common/Menu/MenuList/MenuList.tsx
  frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.stories.tsx
  frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.tsx
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.stories.tsx
  frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.tsx
  frontend/src/hooks/useListKeyboardNavigation.ts
Labels: 💻 프론트엔드, 🔨 리팩터링, 💡 기능

#640 [FE] 잘못된 팀플레이스 ID로 요청하는 것 막는 기능 추가
  frontend/src/apis/http.ts
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/contexts/TeamPlaceContext.tsx
  frontend/src/mocks/handlers/calendar.ts
  frontend/src/mocks/handlers/feed.ts
  frontend/src/mocks/handlers/link.ts
Labels: 🚨 버그, 💻 프론트엔드

#652 [FE] 팀 피드 API 수정
  frontend/src/mocks/fixtures/threads.ts
  frontend/src/mocks/handlers/feed.ts
  frontend/src/types/feed.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#645 [FE] 팀플레이스 내 정보 수정 기능 구현
  frontend/src/apis/team.ts
  frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
  frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.tsx
  frontend/src/hooks/queries/useModifyMyTeamPlaceUserInfo.ts
  frontend/src/hooks/team/useTeamPlaceInfoModal.ts
  frontend/src/hooks/user/useUserInfoModal.ts
  frontend/src/mocks/fixtures/team.ts
  frontend/src/mocks/handlers/team.ts
  frontend/src/types/team.ts
Labels: 💻 프론트엔드, 💡 기능

#654 [FE] 팀 피드 api 수정
  frontend/src/mocks/fixtures/threads.ts
  frontend/src/mocks/handlers/feed.ts
  frontend/src/types/feed.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#647 [FE] 변경된 피드 공지 컴포넌트 UI 구현
  frontend/src/assets/svg/megaphone.svg
  frontend/src/components/feed/NoticeThread/NoticeThread.stories.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/components/team/TeamColorEditModal/TeamColorEditModal.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
  frontend/src/styles/theme.ts
  frontend/src/types/size.ts
Labels: 💻 프론트엔드, 💡 기능

#648 [FE] 역방향 무한스크롤 구현
  frontend/src/components/feed/ThreadList/ThreadList.stories.ts
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#649 [FE] 채팅 메뉴의 이미지 상세 보기 모달 구현
  frontend/src/components/feed/Carousel/Carousel.stories.tsx
  frontend/src/components/feed/Carousel/Carousel.styled.ts
  frontend/src/components/feed/Carousel/Carousel.tsx
  frontend/src/components/feed/PageIndicator/PageIndicator.stories.tsx
  frontend/src/components/feed/PageIndicator/PageIndicator.styled.ts
  frontend/src/components/feed/PageIndicator/PageIndicator.tsx
  frontend/src/components/feed/ThreadImageModal/ThreadImageModal.stories.tsx
  frontend/src/components/feed/ThreadImageModal/ThreadImageModal.styled.ts
  frontend/src/components/feed/ThreadImageModal/ThreadImageModal.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/feed.ts
Labels: 💻 프론트엔드, 💡 기능

#657 [FE] Prefetch를 조건부로 호출하도록 로직 수정
  frontend/src/hooks/queries/usePrefetchSchedules.ts
Labels: 🚨 버그, 💻 프론트엔드

#663 [FE] 팀플레이스 전환 박스 디자인을 변경
  frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.styled.ts
  frontend/src/components/team/TeamPlaceMenu/TeamPlaceMenu.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#666 [FE] 404 페이지 구현
  frontend/src/App.tsx
  frontend/src/assets/webp/error-404-image.webp
  frontend/src/assets/webp/error-404-text.webp
  frontend/src/assets/webp/index.ts
  frontend/src/components/common/BackButton/BackButton.stories.tsx
  frontend/src/components/common/BackButton/BackButton.tsx
  frontend/src/components/common/Error404/Error404.stories.tsx
  frontend/src/components/common/Error404/Error404.styled.ts
  frontend/src/components/common/Error404/Error404.tsx
  frontend/src/components/common/LandingHeader/LandingHeader.tsx
  frontend/src/pages/Error404Page/Error404Page.styled.ts
  frontend/src/pages/Error404Page/Error404Page.tsx
  frontend/src/types/assets.d.ts
  frontend/webpack.config.js
Labels: 💻 프론트엔드, 💡 기능

#660 [FE] 변경된 스레드 컴포넌트 UI 구현
  frontend/src/components/common/DateCell/DateCell.styled.ts
  frontend/src/components/common/ExpandButton/ExpandButton.styled.ts
  frontend/src/components/common/ExpandButton/ExpandButton.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/feed/Thread/Thread.stories.ts
  frontend/src/components/feed/Thread/Thread.styled.ts
  frontend/src/components/feed/Thread/Thread.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.stories.tsx
  frontend/src/constants/feed.ts
  frontend/src/mocks/fixtures/threads.ts
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#664 [BE] 피드스레드 조회 api 응답 수정 및 이벤트 제거, 최적화
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/NotificationService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/presentation/FeedThreadController.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleService.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleCreateEvent.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleDeleteEvent.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleEvent.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleUpdateEvent.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/SharedLinkService.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/SharedLinkCreateEvent.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/SharedLinkDeleteEvent.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/application/event/SharedLinkEvent.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/NotificationServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/schedule/application/TeamCalendarScheduleServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/sharedlink/application/SharedLinkServiceTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 💡 기능, 중요도-중

#668 [FE] 배포환경에 따른 base url 변경
  .github/workflows/deploy-prod-latest.yml
  .github/workflows/frontend-deploy-dev.yml
  frontend/.gitignore
  frontend/package.json
  frontend/src/apis/auth.ts
  frontend/src/apis/http.ts
  frontend/src/index.tsx
Labels: 💻 프론트엔드, 💡 기능

#662 [FE] 채팅 UI 구현
  frontend/src/assets/svg/airplane.svg
  frontend/src/assets/svg/image.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/hooks/team/useTeamFeedPage.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#671 [FE] 배포 스크립트 환경변수 이름 수정
  .github/workflows/deploy-prod-latest.yml
  .github/workflows/frontend-deploy-dev.yml
  frontend/src/apis/http.ts
Labels: 🚨 버그, 💻 프론트엔드, ⚙️ 환경설정

#672 [FE]배포 스크립트 환경변수 파일 수정
  .github/workflows/deploy-prod-latest.yml
  .github/workflows/frontend-deploy-dev.yml
Labels: 🚨 버그, 💻 프론트엔드, ⚙️ 환경설정

#675 [FE] Header 컴포넌트에 Suspense 적용
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/HeaderFallback/HeaderFallback.stories.tsx
  frontend/src/components/common/HeaderFallback/HeaderFallback.styled.ts
  frontend/src/components/common/HeaderFallback/HeaderFallback.tsx
  frontend/src/components/common/Skeleton/Skeleton.stories.tsx
  frontend/src/components/common/Skeleton/Skeleton.styled.ts
  frontend/src/components/common/Skeleton/Skeleton.tsx
  frontend/src/hooks/queries/useFetchUserInfo.ts
  frontend/src/pages/PageTemplate/PageTemplate.tsx
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#681 [FE] CI 스크립트 빌드 명령어 수정
  .github/workflows/frontend-ci.yml
Labels: 🚨 버그, 💻 프론트엔드

#684 [FE] 한글 입력 시 이벤트가 두 번 발생하는 현상 수정
  frontend/src/hooks/team/useTeamFeedPage.ts
Labels: 🚨 버그, 💻 프론트엔드

#665 [FE] 이미지 서랍장 컴포넌트 구현
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.stories.tsx
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.tsx
Labels: 💻 프론트엔드, 💡 기능

#679 [FE] 스레드 없을 시 디자인 수정
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/feed/EmptyFeedPlaceholder/EmptyFeedPlaceholder.styled.ts
  frontend/src/components/feed/EmptyFeedPlaceholder/EmptyFeedPlaceholder.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.tsx
  frontend/src/components/feed/NotificationListModal/NotificationListModal.styled.ts
  frontend/src/components/feed/Thread/Thread.styled.ts
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
  frontend/src/components/user/UserInfoModal/UserInfoModal.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#673 [All] S3에 dist 배포
  .github/workflows/frontend-deploy-dev.yml
Labels: 🍃 백엔드, ⚙️ 환경설정, 🚛배포, 중요도-상

#691 chore: 태그기반 프런트 배포 워크플로우 오류 수정
  .github/workflows/deploy-prod-by-realease-tag.yml
Labels: 🚨 버그, ⚙️ 환경설정, 중요도-상

#687 [FE] 회원 탈퇴 기능 구현
  frontend/src/apis/user.ts
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/warning.svg
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/user/AccountDeleteModal/AccountDeleteModal.stories.tsx
  frontend/src/components/user/AccountDeleteModal/AccountDeleteModal.styled.ts
  frontend/src/components/user/AccountDeleteModal/AccountDeleteModal.tsx
  frontend/src/components/user/UserInfoModal/UserInfoModal.stories.tsx
  frontend/src/components/user/UserInfoModal/UserInfoModal.styled.ts
  frontend/src/components/user/UserInfoModal/UserInfoModal.tsx
  frontend/src/constants/user.ts
  frontend/src/hooks/queries/useDeleteUserAccount.ts
  frontend/src/hooks/user/useAccountDeleteModal.ts
  frontend/src/mocks/handlers/user.ts
Labels: 💻 프론트엔드, 💡 기능

#694 [FE] 팀피드 스레드 크기 수정
  frontend/src/components/feed/Thread/Thread.styled.ts
  frontend/src/components/feed/Thread/Thread.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#698 [FE]리프레쉬 토큰 헤더 저장못하는 문제 확인 작업
  frontend/src/apis/auth.ts
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/hooks/queries/useSendTokenReissue.ts
Labels: 🚨 버그, 💻 프론트엔드

#702 [FE] HeaderSuspense 삭제
  frontend/src/pages/PageTemplate/PageTemplate.tsx
Labels: 🚨 버그, 💻 프론트엔드

#703 [FE] useFetchUserInfo suspense 옵션 제거
  frontend/src/hooks/queries/useFetchUserInfo.ts
Labels: 🚨 버그, 💻 프론트엔드

#706 [BE] 파일관련 패키지 문제 수정
  backend/src/main/java/team/teamby/teambyteam/feed/application/ImageUploadService.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/FileCloudUploader.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/awss3/S3Uploader.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/awss3/configuration/S3Configuration.java
Labels: 🍃 백엔드, 중요도-상

#711 [FE] 공지 md 사이즈에서 글 잘리는 현상
  frontend/src/components/feed/NoticeThread/NoticeThread.stories.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
Labels: 🚨 버그, 💻 프론트엔드

#704 [BE] 회원탈퇴 오류 수정 (회원 탈퇴 이벤트 구현)
  backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
  backend/src/main/java/team/teamby/teambyteam/member/application/event/MemberLeaveEvent.java
  backend/src/main/java/team/teamby/teambyteam/token/application/TokenEventListener.java
  backend/src/main/java/team/teamby/teambyteam/token/domain/TokenRepository.java
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/token/domain/TokenRepositoryTest.java
Labels: 🚨 버그, 🍃 백엔드, 🔨 리팩터링, 중요도-상

#710 [FE] ctrl,alt + enter로 개행기능 추가
  frontend/src/hooks/team/useTeamFeedPage.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#712 [FE] 프런트 배포 후 클라우드프런트 캐시 삭제요청 추가
  .github/workflows/deploy-prod-by-realease-tag.yml
  .github/workflows/deploy-prod-latest.yml
  .github/workflows/frontend-deploy-dev.yml
Labels: 💻 프론트엔드, ⚙️ 환경설정, 🚛배포
