Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2023-10, with the labels that each got.

#693 [FE] 이미지를 로컬에 업로드할 수 있는 기능 구현
  frontend/src/components/feed/DeletableThumbnail/DeletableThumbnail.stories.tsx
  frontend/src/components/feed/DeletableThumbnail/DeletableThumbnail.tsx
  frontend/src/components/feed/ImageAddButton/ImageAddButton.stories.tsx
  frontend/src/components/feed/ImageAddButton/ImageAddButton.styled.ts
  frontend/src/components/feed/ImageAddButton/ImageAddButton.tsx
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.stories.tsx
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.tsx
  frontend/src/components/feed/ThumbnailList/ThumbnailList.stories.tsx
  frontend/src/components/feed/ThumbnailList/ThumbnailList.styled.ts
  frontend/src/components/feed/ThumbnailList/ThumbnailList.tsx
  frontend/src/constants/feed.ts
  frontend/src/hooks/team/useTeamFeedPage.ts
  frontend/src/hooks/thread/useImageUpload.tsx
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
  frontend/src/types/feed.ts
Labels: 💻 프론트엔드, 💡 기능

#716 [FE]일정 제목이 길때 등록안되는 버그
  frontend/src/apis/http.ts
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/hooks/schedule/useScheduleEditModal.ts
  frontend/src/mocks/fixtures/schedules.ts
  frontend/src/mocks/handlers/calendar.ts
Labels: 🚨 버그, 💻 프론트엔드

#732 [FE] DateCell 토/일요일 색상 수정
  frontend/src/components/common/DateCell/DateCell.styled.ts
  frontend/src/components/common/DateCell/DateCell.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#734 [BE] FeedThreadImage PK 전략 IDENTITY (AUTO_INCREMENT)로 수정
  backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImage.java
Labels: 🚨 버그, 🔨 리팩터링, 중요도-상

#735 [FE] 사이드바 UI 수정
  frontend/src/assets/svg/group.svg
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/team-small.svg
  frontend/src/components/common/SideBar/SideBar.styled.ts
  frontend/src/components/common/SideBar/SideBar.tsx
  frontend/src/components/my_calendar/MyCalendar/MyCalendar.styled.ts
  frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
  frontend/src/components/my_calendar/MyDailySchedule/MyDailySchedule.styled.ts
  frontend/src/components/my_calendar/MyDailySchedule/MyDailySchedule.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#737 [BE] build 시 timezone setting 추가
  .github/workflows/backend-ci.yml
Labels: ⚙️ 환경설정, 중요도-상

#738 [BE] S3업로드 후 배포 도메인 반환 오류 수정
  backend/src/main/java/team/teamby/teambyteam/filesystem/awss3/S3Uploader.java
Labels: 🚨 버그, 🍃 백엔드, 중요도-상

#726 [FE] ICalendar 내보내기 기능 구현
  frontend/src/apis/http.ts
  frontend/src/apis/schedule.ts
  frontend/src/assets/svg/export.svg
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/question.svg
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/components/common/Spacing/Spacing.styled.ts
  frontend/src/components/common/Spacing/Spacing.tsx
  frontend/src/components/common/Toast/Toast.styled.ts
  frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.stories.tsx
  frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
  frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.styled.ts
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/constants/calendar.ts
  frontend/src/hooks/queries/useFetchICalendarUrl.ts
  frontend/src/index.tsx
  frontend/src/mocks/handlers/calendar.ts
Labels: 💻 프론트엔드, 🔨 리팩터링, 💡 기능

#740 [BE] 공지 등록 api 리팩토링
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/ImageUploadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedThreadWritingRequest.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/AllowedImageExtension.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/util/FileUtil.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeRegisterRequest.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/Notice.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/image/NoticeImage.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/image/NoticeImageRepository.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/image/vo/ImageName.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/image/vo/ImageUrl.java
  backend/src/main/java/team/teamby/teambyteam/notice/exception/NoticeException.java
  backend/src/main/java/team/teamby/teambyteam/notice/presentation/NoticeController.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/FeedThreadFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/FileFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/NoticeFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/FeedThreadAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/NoticeAcceptanceFixtures.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/docs/NoticeApiDocsTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 💡 기능, 중요도-상

#723 [BE] 피드에서 이미지 조회 기능 구현
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedThread.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImage.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImageRepository.java
  backend/src/main/java/team/teamby/teambyteam/global/configuration/ClockConfiguration.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/BuilderSupporter.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/FeedThreadFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/FeedThreadImageFixtures.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
Labels: 🍃 백엔드, 💡 기능, 중요도-상

#727 [FE] 이미지 포함한 스레드 등록 구현
  frontend/src/apis/feed.ts
  frontend/src/apis/http.ts
  frontend/src/components/feed/ThreadAddBottomSheet/ThreadAddBottomSheet.stories.tsx
  frontend/src/components/feed/ThreadAddBottomSheet/ThreadAddBottomSheet.styled.ts
  frontend/src/components/feed/ThreadAddBottomSheet/ThreadAddBottomSheet.tsx
  frontend/src/hooks/queries/useSendNoticeThread.ts
  frontend/src/hooks/queries/useSendThread.ts
  frontend/src/hooks/thread/useTeamFeedPage.ts
  frontend/src/hooks/thread/useThreadAddBottomSheet.ts
  frontend/src/mocks/handlers/feed.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
  frontend/src/types/feed.ts
Labels: 💻 프론트엔드, 💡 기능

#743 [FE] 스레드 등록이 안되는 버그
  frontend/src/apis/http.ts
Labels: 🚨 버그, 💻 프론트엔드

#741 [BE] Icalendar 테스트 수정
  backend/src/test/java/team/teamby/teambyteam/icalendar/acceptance/IcalendarAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarEventListenerTest.java
Labels: 🍃 백엔드, 🤖 테스트, 중요도-하

#733 [FE] 스레드에서 이미지를 조회할 수 있는 기능 추가
  frontend/src/components/common/ExpandButton/ExpandButton.stories.tsx
  frontend/src/components/common/ExpandButton/ExpandButton.styled.ts
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.stories.tsx
  frontend/src/components/feed/NoticeThread/NoticeThread.styled.ts
  frontend/src/components/feed/NoticeThread/NoticeThread.tsx
  frontend/src/components/feed/Thread/Thread.stories.ts
  frontend/src/components/feed/Thread/Thread.styled.ts
  frontend/src/components/feed/Thread/Thread.tsx
  frontend/src/components/feed/ThreadExpandButton/ThreadExpandButton.stories.tsx
  frontend/src/components/feed/ThreadExpandButton/ThreadExpandButton.styled.ts
  frontend/src/components/feed/ThreadExpandButton/ThreadExpandButton.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/components/feed/ThumbnailList/ThumbnailList.stories.tsx
  frontend/src/components/feed/ThumbnailList/ThumbnailList.styled.ts
  frontend/src/components/feed/ThumbnailList/ThumbnailList.tsx
  frontend/src/components/feed/ViewableThumbnail/ViewableThumbnail.stories.tsx
  frontend/src/components/feed/ViewableThumbnail/ViewableThumbnail.styled.ts
  frontend/src/components/feed/ViewableThumbnail/ViewableThumbnail.tsx
  frontend/src/hooks/thread/useThreadHeight.ts
  frontend/src/mocks/fixtures/threads.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 💡 기능

#745 [BE] 공지 조회 api 리팩토링
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeImageResponse.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeResponse.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/image/NoticeImage.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/BuilderSupporter.java
  backend/src/test/java/team/teamby/teambyteam/common/builder/TestFixtureBuilder.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/NoticeFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/NoticeImageFixtures.java
  backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/docs/NoticeApiDocsTest.java
  backend/src/test/resources/h2-truncate.sql
Labels: 🍃 백엔드, 🔨 리팩터링

#747 [FE] 팀 캘린더에 오늘 표시 추가
  frontend/src/components/my_calendar/MyCalendar/MyCalendar.tsx
  frontend/src/components/team_calendar/TeamCalendar/TeamCalendar.tsx
  frontend/src/hooks/useCalendar.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#751 [BE] 파일 업로드 시 content-type 추가
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/ImageUploadService.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/FileCloudUploader.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/awss3/S3Uploader.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishService.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/icalendar/acceptance/IcalendarAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/icalendar/application/IcalendarPublishServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/docs/NoticeApiDocsTest.java
Labels: 🚨 버그, 🍃 백엔드, 중요도-상

#760 [FE] sse 연결 코드 작성
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/queries/useSSE.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
  frontend/src/types/polyfill.ts
Labels: 💻 프론트엔드, 💡 기능

#761 [FE] SSE 연결 해제 코드 작성
  frontend/src/hooks/queries/useSSE.ts
Labels: 💻 프론트엔드, 💡 기능

#763 [BE] SSE 이벤트 발행시 팀플레이스로 검사 오류 수정
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterId.java
Labels: 🚨 버그, 🍃 백엔드, 중요도-상

#762 [FE] SSE 연결 확인 코드 작성
  frontend/src/hooks/queries/useSSE.ts
  frontend/src/types/polyfill.d.ts
  frontend/src/types/polyfill.ts
Labels: 💻 프론트엔드, 💡 기능

#764 [FE] 새로운 스레드 등록 시 스크롤 하단으로 이동 구현
  frontend/src/hooks/queries/useSSE.ts
  frontend/src/hooks/thread/useTeamFeedPage.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#765 [FE] SSE 이벤트 수신 시 스크롤 로직 제거
  frontend/src/hooks/queries/useSSE.ts
Labels: 💻 프론트엔드, 💡 기능

#767 [BE] SSE 문제 해결을 위한 로깅 및 리펙터링
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/event/FeedEvent.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/event/FeedWriteEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/application/SseSubscribeService.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceConnectedEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java
  backend/src/test/java/team/teamby/teambyteam/sse/application/SseSubscribeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisherTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepositoryTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-상

#766 [FE] 채팅 입력 시 스크롤 로직을 ResizeObserver로 리팩터링
  frontend/src/hooks/queries/useSSE.ts
  frontend/src/hooks/thread/useTeamFeedPage.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#771 [FE] 에러발생시 연결 끊는로직 제거
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#775 [FE] 스크롤 로직을 useEffect를 사용하도록 수정
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/hooks/thread/useTeamFeedPage.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 🚨 버그, 💻 프론트엔드

#770 [FE] git page로 storybook 배포
  .github/workflows/frontend-deploy-storybook.yml
Labels: 💻 프론트엔드, 💡 기능

#776 [FE] 스크롤 버튼이 보이는 경우 새로운 채팅이 등록되어도 스크롤이 내려가지 않도록 수정
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#780 [FE] queryClient가 계속 새로 생성되는 로직 수정
  frontend/src/index.tsx
Labels: 🚨 버그, 💻 프론트엔드

#779 [FE] 팀링크 등록이 제대로 되지않는 문제
  frontend/src/assets/svg/bell.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/HeaderFallback/HeaderFallback.tsx
  frontend/src/components/feed/NotificationListModal/NotificationListModal.stories.tsx
  frontend/src/components/feed/NotificationListModal/NotificationListModal.styled.ts
  frontend/src/components/feed/NotificationListModal/NotificationListModal.tsx
  frontend/src/hooks/queries/useDeleteSchedule.ts
  frontend/src/hooks/queries/useDeleteTeamLink.ts
  frontend/src/hooks/queries/useFetchNotifications.ts
  frontend/src/hooks/queries/useModifySchedule.ts
  frontend/src/hooks/queries/useSendSchedule.ts
  frontend/src/hooks/queries/useSendTeamLink.ts
Labels: 🚨 버그, 💻 프론트엔드

#783 [FE] 재발급된 토큰으로 sse연결 요청하기
  frontend/src/hooks/queries/useSSE.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 🚨 버그, 💻 프론트엔드

#777 [FE] 이미지가 깨지는 경우에 대해 적절히 예외처리 할 수 있도록 개선
  frontend/src/components/feed/Carousel/Carousel.styled.ts
  frontend/src/components/feed/Carousel/Carousel.tsx
  frontend/src/components/feed/CarouselImage/CarouselImage.stories.tsx
  frontend/src/components/feed/CarouselImage/CarouselImage.styled.ts
  frontend/src/components/feed/CarouselImage/CarouselImage.tsx
  frontend/src/components/feed/DeletableThumbnail/DeletableThumbnail.tsx
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
  frontend/src/components/feed/PageIndicator/PageIndicator.styled.ts
  frontend/src/components/feed/ThreadImageModal/ThreadImageModal.styled.ts
  frontend/src/components/feed/ViewableThumbnail/ViewableThumbnail.tsx
  frontend/src/mocks/fixtures/threads.ts
  frontend/src/styles/theme.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#786 [BE] SSE emitter 예외시 행위 수정
  backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java
Labels: 🚨 버그, 🍃 백엔드, 🔨 리팩터링, 중요도-상

#785 [FE] SSE 재연결하는 로직 수정
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#789 [FE] 에러 발생시 sse 연결닫기
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#790 [FE] useState 제거
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#793 [FE] 스토리북 배포 후 404 뜨는 문제 해결
  .github/workflows/frontend-deploy-storybook.yml
Labels: 🚨 버그, 💻 프론트엔드

#794 [BE] SSE 에러시 completeWithError 추가
  backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-중

#795 [FE] SSE 연결 로직 useCallback으로 감싸기
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#797 [FE] sse 문제 해결
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#798 [FE] console.log 확인
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#800 [FE] SSE 재연결 시도 로직 작성
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#801 [FE] useSSE onerror 제거
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#802 [FE] storybook workflow publish_dir 경로 변경
  .github/workflows/frontend-deploy-storybook.yml
Labels: 🚨 버그, 💻 프론트엔드, 🚛배포

#803 [FE] SSE 토큰 갱신 로직 수정
  frontend/src/hooks/queries/useSSE.ts
Labels: 🚨 버그, 💻 프론트엔드

#804 [BE] io예외시에 커넥션 종료시키는 기능 추가
  backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
Labels: 🚨 버그, 🍃 백엔드, 중요도-상

#808 [BE] SSE 예외처리 추가
  backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
Labels: 🚨 버그, 🍃 백엔드, 중요도-상

#807 [FE] accessToken 설정, 삭제하는 로직 tokenContext로 대체
  frontend/src/components/common/ProtectRoute/ProtectRoute.tsx
  frontend/src/contexts/TokenContext.tsx
  frontend/src/hooks/queries/useSSE.ts
  frontend/src/hooks/queries/useSendTokenReissue.ts
  frontend/src/hooks/user/useAccountDeleteModal.ts
  frontend/src/hooks/user/useUserInfoModal.ts
  frontend/src/pages/Error404Page/Error404Page.tsx
  frontend/src/pages/LandingPage/LandingPage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#788 [FE] 이미지 전송 중 전송 버튼 비활성화
  frontend/src/assets/svg/airplane.svg
  frontend/src/components/feed/DeletableThumbnail/DeletableThumbnail.stories.tsx
  frontend/src/components/feed/DeletableThumbnail/DeletableThumbnail.tsx
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.stories.tsx
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.tsx
  frontend/src/components/feed/ThumbnailList/ThumbnailList.stories.tsx
  frontend/src/components/feed/ThumbnailList/ThumbnailList.tsx
  frontend/src/hooks/queries/useSendNoticeThread.ts
  frontend/src/hooks/queries/useSendThread.ts
  frontend/src/hooks/thread/useTeamFeedPage.ts
  frontend/src/mocks/handlers/feed.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 💻 프론트엔드, 💡 기능

#809 [FE] Schedule 관련 모달 디자인 수정
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#810 [FE] 링크 관련 디자인 수정
  frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
  frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
  frontend/src/components/link/LinkTable/LinkTable.styled.ts
  frontend/src/components/link/LinkTable/LinkTable.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#811 [FE] 모아보기 페이지에서 링크 등록 모달 잘리는 현상 수정
  frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#815 [FE] 등록 성공 시 조회 쿼리 무효화 구문 삭제
  frontend/src/hooks/queries/useSendNoticeThread.ts
  frontend/src/hooks/queries/useSendThread.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#812 [FE] iCalendar url에 placeholder 적용하여 빈 input을 보지 않도록 수정
  frontend/src/hooks/queries/useFetchICalendarUrl.ts
  frontend/src/mocks/handlers/calendar.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#816 [ALL] README 업데이트
  README.md
Labels: 🍃 백엔드, 💻 프론트엔드, 📑 문서

#818 [BE] 피드 최신조회에 인메모리 캐싱 추가
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/cache/InMemoryRecentFeedCache.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/cache/RecentFeedCache.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadWithCacheServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/domain/cache/InMemoryRecentFeedCacheTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-중

#819 [BE] 캐싱 비활성화
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedThreadService.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadWithCacheServiceTest.java
Labels: 🚨 버그, 🍃 백엔드, 중요도-상

#821 [BE] SSE 이벤트 발행을 비동기로 처리
  backend/src/main/java/team/teamby/teambyteam/sse/domain/SseEmitters.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceEmitterRepository.java
  backend/src/test/java/team/teamby/teambyteam/sse/application/SseSubscribeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisherTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-상

#823 [FE] 공지 등록 후 공지 쿼리 무효화 추가
  frontend/src/hooks/queries/useSendNoticeThread.ts
Labels: 🚨 버그, 💻 프론트엔드

#825 [FE] Menu가 focus 된 경우 위/아래 방향키 입력 시 열리도록 구현
  frontend/src/components/common/Menu/MenuButton/MenuButton.tsx
Labels: 💻 프론트엔드, 💡 기능

#828 [FE] 검색 결과에 대한 정보 제공을 위한 meta tag 추가
  frontend/public/index.html
Labels: 💻 프론트엔드, 💡 기능

#830 [FE] 테스트, 빌드 속도 개선
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.js
Labels: 💻 프론트엔드, 🔨 리팩터링, ⚙️ 환경설정

#832 [FE] React Query staleTime을 적용하여 네트워크 요청 횟수를 줄인다.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/query.ts
  frontend/src/hooks/queries/useFetchDailySchedules.ts
  frontend/src/hooks/queries/useFetchICalendarUrl.ts
  frontend/src/hooks/queries/useFetchMyDailySchedule.ts
  frontend/src/hooks/queries/useFetchMySchedules.ts
  frontend/src/hooks/queries/useFetchSchedules.ts
  frontend/src/hooks/queries/useFetchTeamLinks.ts
  frontend/src/hooks/queries/useFetchTeamPlaceInviteCode.ts
  frontend/src/hooks/queries/useFetchTeamPlaceMembers.ts
  frontend/src/hooks/queries/useFetchUserInfo.ts
  frontend/src/hooks/queries/usePrefetchSchedules.ts
  frontend/src/index.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링
