Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2024-03, with the labels that each got.

#938 [FE] 알림 컴포넌트의 UI를 변경하고, 채팅을 입력한 날짜를 알림 컴포넌트를 활용하여 알리도록 개선
  frontend/src/assets/svg/enter.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/feed/Notification/Notification.stories.ts
  frontend/src/components/feed/Notification/Notification.stories.tsx
  frontend/src/components/feed/Notification/Notification.styled.ts
  frontend/src/components/feed/Notification/Notification.tsx
  frontend/src/components/feed/Thread/Thread.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/hooks/thread/useFirstDateTime.ts
  frontend/src/types/feed.ts
  frontend/src/utils/formatDate.ts
  frontend/src/utils/splitDateTime.ts
Labels: 💻 프론트엔드, 💡 기능

#954 [FE] 팀 피드/팀 링크에서의 최상위 도메인명 조건 완화
  frontend/src/components/feed/Thread/Thread.stories.ts
  frontend/src/constants/link.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#937 [FE] 팀바팀 전반적인 모달 사이즈 조정
  frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
  frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
  frontend/src/components/team/TeamExitModal/TeamExitModal.styled.ts
  frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.styled.ts
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.tsx
  frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
  frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.stories.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.styled.ts
Labels: 💻 프론트엔드, 🔨 리팩터링

#956 [BE] 팀채팅시 이벤트 발행에 db조회 제거
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedReadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/event/FeedEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverter.java
  backend/src/test/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverterTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-상

#958 [ALL] Release v1.7.0
  .github/workflows/backend-deploy-dev-docs.yml
  .github/workflows/backend-deploy-dev.yml
  README.md
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedReadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/event/FeedEvent.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleResponse.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverter.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverterTest.java
  frontend/src/assets/svg/enter.svg
  frontend/src/assets/svg/index.ts
  frontend/src/components/feed/Notification/Notification.stories.ts
  frontend/src/components/feed/Notification/Notification.stories.tsx
  frontend/src/components/feed/Notification/Notification.styled.ts
  frontend/src/components/feed/Notification/Notification.tsx
  frontend/src/components/feed/Thread/Thread.stories.ts
  frontend/src/components/feed/Thread/Thread.tsx
  frontend/src/components/feed/ThreadList/ThreadList.tsx
  frontend/src/components/link/LinkAddModal/LinkAddModal.styled.ts
  frontend/src/components/link/LinkAddModal/LinkAddModal.tsx
  frontend/src/components/team/TeamExitModal/TeamExitModal.styled.ts
  frontend/src/components/team/TeamPlaceInfoModal/TeamPlaceInfoModal.styled.ts
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.styled.ts
  frontend/src/components/team_calendar/DailyScheduleModal/DailyScheduleModal.tsx
  frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.styled.ts
  frontend/src/components/team_calendar/ICalendarModal/ICalendarModal.tsx
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.stories.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.styled.ts
  frontend/src/constants/link.ts
  frontend/src/hooks/thread/useFirstDateTime.ts
  frontend/src/types/feed.ts
  frontend/src/utils/formatDate.ts
  frontend/src/utils/splitDateTime.ts
Labels: 🚛배포, 중요도-상

#961 [BE] common-global package 분배, 일부 양방향 의존 해결
  backend/src/main/java/team/teamby/teambyteam/common/domain/BaseEntity.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/Feed.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImage.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/exception/FileControlException.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/util/FileUtil.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/domain/PublishedIcalendar.java
  backend/src/main/java/team/teamby/teambyteam/member/application/MemberService.java
  backend/src/main/java/team/teamby/teambyteam/member/application/dto/MemberUpdateRequest.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/Member.java
  backend/src/main/java/team/teamby/teambyteam/member/domain/MemberTeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/member/presentation/MemberController.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/Notice.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/image/NoticeImage.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/domain/SharedLink.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlace.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/domain/TeamPlaceInviteCode.java
  backend/src/main/java/team/teamby/teambyteam/token/domain/Token.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/acceptance/MemberAcceptanceFixture.java
  backend/src/test/java/team/teamby/teambyteam/member/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/member/application/MemberServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/sharedlink/application/SharedLinkServiceTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-중

#963 [BE] 오타수정
  backend/src/main/java/team/teamby/teambyteam/common/exception/CustomNotFondException.java
  backend/src/main/java/team/teamby/teambyteam/common/exception/CustomNotFoundException.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/GlobalExceptionHandler.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/exception/IcalendarNotFoundException.java
  backend/src/main/java/team/teamby/teambyteam/member/exception/MemberNotFoundException.java
  backend/src/main/java/team/teamby/teambyteam/schedule/exception/ScheduleNotFoundException.java
  backend/src/main/java/team/teamby/teambyteam/sharedlink/exception/SharedLinkNotFoundException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/exception/TeamPlaceNotFoundException.java
  backend/src/main/java/team/teamby/teambyteam/teamplace/exception/invitecode/TeamPlaceInviteCodeNotFoundException.java
Labels: 🍃 백엔드
