Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2024-02, with the labels that each got.

#914 [BE] Refactor 피드 서비스 리팩터링
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedReadService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/NotificationService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedImageResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedThreadWritingRequest.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/FeedRepository.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/cache/InMemoryRecentFeedCache.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/cache/RecentFeedCache.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImage.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/image/vo/ImageName.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/image/vo/ImageUrl.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/notification/schedulenotification/ScheduleNotificationFactory.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/vo/Content.java
  backend/src/main/java/team/teamby/teambyteam/feed/presentation/FeedThreadController.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedReadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedThreadWithCacheServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedWriteServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/NotificationServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/domain/cache/InMemoryRecentFeedCacheTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/domain/vo/ContentTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-중

#915 [BE] SSE 이벤트 발행 패키지 의존성 방향 변경
  backend/src/main/java/team/teamby/teambyteam/common/domain/DomainEvent.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedResponse.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/event/FeedEvent.java
  backend/src/main/java/team/teamby/teambyteam/schedule/application/event/ScheduleEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/application/SseSubscribeService.java
  backend/src/main/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisher.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceConnectedSseEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/TeamPlaceSseEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverter.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/TeamPlaceEventConvertMapper.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/TeamPlaceSseConverter.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/emitter/SseEmitters.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/emitter/TeamPlaceEmitterId.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/emitter/TeamPlaceEmitterRepository.java
  backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/TestSseEvent.java
  backend/src/test/java/team/teamby/teambyteam/sse/application/SseSubscribeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisherTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverterTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/domain/emitter/TeamPlaceEmitterRepositoryTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-상

#916 [BE] SSE이벤트 발행시 Json Parsing 에러 해결
  backend/src/main/java/team/teamby/teambyteam/sse/domain/emitter/SseEmitters.java
Labels: 🚨 버그, 🍃 백엔드, 중요도-상

#917 [ALL] 배포 워크플로우 수정
  .github/workflows/backend-ci.yml
  .github/workflows/backend-deploy-dev-docs.yml
  .github/workflows/backend-deploy-dev.yml
  .github/workflows/deploy-prod-by-realease-tag.yml
  .github/workflows/deploy-prod-latest.yml
  .github/workflows/frontend-ci.yml
  .github/workflows/frontend-deploy-dev.yml
  .github/workflows/frontend-deploy-storybook.yml
Labels: 🍃 백엔드, 💻 프론트엔드, 🚛배포, 중요도-중

#919 [BE] sparse checkout 위치 변경
  .github/workflows/backend-deploy-dev.yml
  .github/workflows/deploy-prod-by-realease-tag.yml
  .github/workflows/deploy-prod-latest.yml
Labels: 🚨 버그, 🍃 백엔드, 🚛배포

#921 [BE] 배포 워크플로우 실행 순서 변경
  .github/workflows/backend-deploy-dev.yml
  .github/workflows/deploy-prod-by-realease-tag.yml
  .github/workflows/deploy-prod-latest.yml
Labels: 🚨 버그, 🍃 백엔드, 🚛배포, 중요도-상

#925 [BE] 팀플레이스 공지 등록시 실시간 SSE 알림 추가
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/NoticeRepository.java
  backend/src/main/java/team/teamby/teambyteam/notice/domain/event/NoticeCreationEvent.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/FeedEventConverter.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/NoticeCreatedEventConverter.java
  backend/src/main/java/team/teamby/teambyteam/sse/domain/converter/TeamPlaceSseConverter.java
  backend/src/test/java/team/teamby/teambyteam/notice/application/NoticeServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisherTest.java
  backend/src/test/java/team/teamby/teambyteam/sse/domain/converter/NoticeCreatedEventConverterTest.java
Labels: 🍃 백엔드, 💡 기능, 중요도-중

#928 [BE] 누락된 SSE 이벤트 발행 추가
  backend/src/main/java/team/teamby/teambyteam/sse/application/TeamPlaceSsePublisher.java
Labels: 🚨 버그, 🍃 백엔드, 중요도-상

#934 [FE] 모바일에서 채팅 입력창에 자동으로 포커스 하지 않도록 변경
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#935 [FE] 하루 전체 일정에서 쿼리 매개변수 형식 변경
  frontend/src/hooks/queries/useFetchDailySchedules.ts
Labels: 🚨 버그, 💻 프론트엔드

#932 [FE] 첫 로드 후 조회 요청 없이 채팅을 치면 조회가 안되는 버그
  frontend/src/hooks/queries/useFetchThreads.ts
Labels: 🚨 버그, 💻 프론트엔드

#946 [BE] ics 배포과정 로깅 추가
  backend/src/main/java/team/teamby/teambyteam/icalendar/application/PeriodicIcalendarPublishService.java
Labels: 🍃 백엔드, 중요도-중

#947 [BE] Schedule Description null 가능성 제거
  backend/src/main/java/team/teamby/teambyteam/icalendar/domain/ical4j/ICal4jParser.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/domain/ical4j/VEventParser.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
Labels: 🚨 버그, 🍃 백엔드, 중요도-상

#949 [ALL] 리드미 Release 버젼 변경
  README.md
Labels: 📑 문서

#950 Release 1.6.5
  README.md
  backend/src/main/java/team/teamby/teambyteam/icalendar/application/PeriodicIcalendarPublishService.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/domain/ical4j/ICal4jParser.java
  backend/src/main/java/team/teamby/teambyteam/icalendar/domain/ical4j/VEventParser.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
Labels: 🚛배포, 중요도-상

#948 [BE] schedule response에 description 추가
  backend/src/main/java/team/teamby/teambyteam/schedule/application/dto/ScheduleResponse.java
  backend/src/main/java/team/teamby/teambyteam/schedule/domain/Schedule.java
  backend/src/test/java/team/teamby/teambyteam/schedule/docs/TeamCalendarScheduleApiDocsTest.java
Labels: 🍃 백엔드, 💡 기능, 📑 문서, 중요도-중

#951 [BE] api 문서 배포 워크플로우 수정
  .github/workflows/backend-deploy-dev-docs.yml
  .github/workflows/backend-deploy-dev.yml
Labels: 🍃 백엔드, 🚛배포, 중요도-중

#952 [BE] api문서 배포 워크플로우 실행 버튼 추가
  .github/workflows/backend-deploy-dev-docs.yml
Labels: 🍃 백엔드, 🚛배포, 중요도-중
