Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2024-01, with the labels that each got.

#903 [FE] 일정 생성/수정 모달에서 날짜 또는 시간 변경 시 편의를 위한 자동 값 변경 기능 구현
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/hooks/schedule/useDateTimeRange.ts
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/hooks/schedule/useScheduleEditModal.ts
  frontend/src/types/schedule.ts
  frontend/src/types/typeGuard.ts
  frontend/src/utils/generateYYYYMMDD.ts
  frontend/src/utils/generateYYYYMMDDHHMM.ts
Labels: 💻 프론트엔드, 💡 기능

#899 [FE] 스크롤 useEffect에서 threadPage 수 비교 로직 삭제
  frontend/src/components/feed/ThreadList/ThreadList.tsx
Labels: 🚨 버그, 💻 프론트엔드

#908 [FE] 통합하루일정이 변경된 API 명세와 다르게 요청하는 문제
  frontend/src/components/my_calendar/MyDailyScheduleList/MyDailyScheduleList.tsx
  frontend/src/hooks/queries/useFetchMyDailySchedule.ts
Labels: 🚨 버그, 💻 프론트엔드

#909 [FE] 채팅 스크롤 버그 픽스
  frontend/src/components/feed/ThreadList/ThreadList.tsx
Labels: 🚨 버그, 💻 프론트엔드

#901 [FE] 모바일에서 하단 메뉴 잘리는 버그 픽스
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/common/Header/Header.styled.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/NavigationBar/NavigationBar.styled.ts
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.stories.tsx
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.styled.ts
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.tsx
  frontend/src/components/feed/Thread/Thread.styled.ts
  frontend/src/mobilePages/M_PageTemplate/M_PageTemplate.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.styled.ts
  frontend/src/pages/TeamFeedPage/TeamFeedPage.tsx
Labels: 🚨 버그, 💻 프론트엔드, 🔨 리팩터링

#910 [ALL] Release 1.6.0
  README.md
Labels: 📑 문서, 🚛배포, 중요도-상

#912 [FE] ThreadList에 존재하는 console.log 제거
  frontend/src/components/feed/ThreadList/ThreadList.tsx
Labels: 💻 프론트엔드, 🔨 리팩터링

#913 [ALL] README gif수정 및 내용 순서 변경
  README.md
Labels: 🍃 백엔드, 💻 프론트엔드, 📑 문서
