Repository woowacourse-teams/2023-team-by-team, pull requests merged in 2025-01, with the labels that each got.

#978 [BE] 이미지 검증로직 변경
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/dto/FeedThreadWritingRequest.java
  backend/src/main/java/team/teamby/teambyteam/feed/exception/FeedImageOverCountException.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/ImageValidationService.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/exception/ImageSizeException.java
  backend/src/main/java/team/teamby/teambyteam/filesystem/exception/NotAllowedImageExtensionException.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/NoticeService.java
  backend/src/main/java/team/teamby/teambyteam/notice/application/dto/NoticeRegisterRequest.java
  backend/src/main/java/team/teamby/teambyteam/notice/exception/NoticeImageOverCountException.java
  backend/src/main/java/team/teamby/teambyteam/notice/exception/NoticeImageSizeException.java
  backend/src/main/java/team/teamby/teambyteam/notice/exception/NoticeNotAllowedImageExtensionException.java
  backend/src/test/java/team/teamby/teambyteam/feed/acceptance/FeedThreadAcceptanceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedWriteServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/notice/acceptance/NoticeAcceptanceTest.java
Labels: 🍃 백엔드, 🔨 리팩터링, 중요도-중

#982 [FE] 잘못된 msw 활성화 조건을 올바르게 수정
  frontend/src/index.tsx
Labels: 🚨 버그

#980 [BE] 이미지(만) 업로드하는 api 추가
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedImageService.java
  backend/src/main/java/team/teamby/teambyteam/feed/application/FeedWriteService.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/image/FeedThreadImage.java
  backend/src/main/java/team/teamby/teambyteam/feed/domain/image/Status.java
  backend/src/main/java/team/teamby/teambyteam/feed/presentation/FeedThreadController.java
  backend/src/main/java/team/teamby/teambyteam/feed/presentation/dto/FeedImagesResponse.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/FeedThreadFixtures.java
  backend/src/test/java/team/teamby/teambyteam/common/fixtures/FeedThreadImageFixtures.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedImageServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedReadServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/application/FeedWriteServiceTest.java
  backend/src/test/java/team/teamby/teambyteam/feed/docs/FeedThreadApiDocsTest.java
Labels: 🍃 백엔드, 💡 기능, 중요도-상

#977 [BE] websocket configuration
  backend/build.gradle
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebSocketConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/ConnectInboundChannelInterceptor.java
Labels: 🍃 백엔드, ⚙️ 환경설정, 중요도-상

#984 [BE] websocket configuration (#977)(Action 실패로 인한 재PR)
  backend/build.gradle
  backend/src/main/java/team/teamby/teambyteam/global/configuration/WebSocketConfiguration.java
  backend/src/main/java/team/teamby/teambyteam/global/presentation/ConnectInboundChannelInterceptor.java
Labels: 🍃 백엔드

#981 [FE] 캘린더 메모 기능 추가
  frontend/.babelrc.json
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/svg/index.ts
  frontend/src/assets/svg/memo.svg
  frontend/src/components/common/BackButton/BackButton.stories.tsx
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Checkbox/Checkbox.stories.tsx
  frontend/src/components/common/Error404/Error404.stories.tsx
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/LandingHeader/LandingHeader.stories.tsx
  frontend/src/components/common/Svg/Svg.styled.ts
  frontend/src/components/common/Svg/Svg.tsx
  frontend/src/components/common/Switch/Switch.stories.tsx
  frontend/src/components/common/Switch/Switch.styled.ts
  frontend/src/components/common/Switch/Switch.tsx
  frontend/src/components/feed/Carousel/Carousel.stories.tsx
  frontend/src/components/feed/CarouselImage/CarouselImage.stories.tsx
  frontend/src/components/feed/DeletableThumbnail/DeletableThumbnail.stories.tsx
  frontend/src/components/feed/EmptyFeedPlaceholder/EmptyFeedPlaceholder.stories.tsx
  frontend/src/components/feed/ImageAddButton/ImageAddButton.stories.tsx
  frontend/src/components/feed/ImageUploadDrawer/ImageUploadDrawer.stories.tsx
  frontend/src/components/feed/PageIndicator/PageIndicator.stories.tsx
  frontend/src/components/feed/ThreadImageModal/ThreadImageModal.stories.tsx
  frontend/src/components/feed/ThumbnailList/ThumbnailList.stories.tsx
  frontend/src/components/feed/ViewableThumbnail/ViewableThumbnail.stories.tsx
  frontend/src/components/landing/FeedDecoration/FeedDecoration.stories.tsx
  frontend/src/components/landing/FileDriveDecoration/FileDriveDecoration.stories.tsx
  frontend/src/components/landing/IntroCardPile/IntroCardPile.stories.tsx
  frontend/src/components/landing/TeamCalendarDecoration/TeamCalendarDecoration.stories.tsx
  frontend/src/components/link/EmptyLinkPlaceholder/EmptyLinkPlaceholder.stories.tsx
  frontend/src/components/link/LinkTable/LinkTable.stories.tsx
  frontend/src/components/team_calendar/FakeScheduleBarsScreen/FakeScheduleBarsScreen.stories.tsx
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.styled.ts
  frontend/src/components/team_calendar/ScheduleAddModal/ScheduleAddModal.tsx
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.styled.ts
  frontend/src/components/team_calendar/ScheduleEditModal/ScheduleEditModal.tsx
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.styled.ts
  frontend/src/components/team_calendar/ScheduleModal/ScheduleModal.tsx
  frontend/src/components/team_calendar/TimeTableMenu/TimeTableMenu.styled.ts
  frontend/src/components/user/AccountDeleteModal/AccountDeleteModal.stories.tsx
  frontend/src/constants/calendar.ts
  frontend/src/hooks/schedule/useDateTimeRange.ts
  frontend/src/hooks/schedule/useScheduleAddModal.ts
  frontend/src/hooks/schedule/useScheduleEditModal.ts
  frontend/src/mocks/fixtures/schedules.ts
  frontend/src/mocks/handlers/calendar.ts
  frontend/src/mocks/handlers/user.ts
  frontend/src/types/schedule.ts
  frontend/src/types/size.ts
Labels: 💻 프론트엔드, 💡 기능, ⚙️ 환경설정
